```
Topic:        Challenge Set 9
Subject:      Part II: Baseball Data
Date:         10/19/2019
Name:         Kristen Tokunaga
Worked with:  N/A
```

In [1]:
#Connect to AWS machine--which is storing baseballdata and we also installed SQL during AWS setup

from psycopg2 import connect
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

params = {
    'host': '34.221.232.83', #can use Amazon IP and user = ubuntu... OR 127.0.0.1 for your local machine
    'user': 'ubuntu', #local, so don't need port
    'port': 5432
}

from sqlalchemy import create_engine
connection = connect(**params, dbname='baseball')
cursor = connection.cursor()

In [2]:
#Inspect can help view all columns in the table

from sqlalchemy import inspect
engine = create_engine('postgresql://ubuntu:password@34.221.232.83/baseball')
inspector = inspect(engine)
inspector.get_columns('salaries')

[{'name': 'yearid',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'teamid',
  'type': VARCHAR(length=3),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'lgid',
  'type': VARCHAR(length=2),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'playerid',
  'type': VARCHAR(length=9),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'salary',
  'type': DOUBLE_PRECISION(precision=53),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None}]

# What was the total spent on salaries by each team, each year?

In [3]:
#LIMIT and ORDER were not specified in the question--so I did not set a limit and chose my own order
query = """
rollback;
SELECT SUM(salary), teamid, yearid 
FROM salaries
GROUP BY teamid, yearid
ORDER BY teamid, yearid;
"""
cursor.execute(query)
cursor.fetchall()

[(31135472.0, 'ANA', 1997),
 (41281000.0, 'ANA', 1998),
 (55388166.0, 'ANA', 1999),
 (51464167.0, 'ANA', 2000),
 (47535167.0, 'ANA', 2001),
 (61721667.0, 'ANA', 2002),
 (79031667.0, 'ANA', 2003),
 (100534667.0, 'ANA', 2004),
 (32347000.0, 'ARI', 1998),
 (68703999.0, 'ARI', 1999),
 (81027833.0, 'ARI', 2000),
 (85082999.0, 'ARI', 2001),
 (102819999.0, 'ARI', 2002),
 (80657000.0, 'ARI', 2003),
 (69780750.0, 'ARI', 2004),
 (62329166.0, 'ARI', 2005),
 (59684226.0, 'ARI', 2006),
 (52067546.0, 'ARI', 2007),
 (66202712.0, 'ARI', 2008),
 (73115666.0, 'ARI', 2009),
 (60718166.0, 'ARI', 2010),
 (53639833.0, 'ARI', 2011),
 (73804833.0, 'ARI', 2012),
 (90132000.0, 'ARI', 2013),
 (14807000.0, 'ATL', 1985),
 (17102786.0, 'ATL', 1986),
 (16544560.0, 'ATL', 1987),
 (12728174.0, 'ATL', 1988),
 (11112334.0, 'ATL', 1989),
 (14555501.0, 'ATL', 1990),
 (18403500.0, 'ATL', 1991),
 (34625333.0, 'ATL', 1992),
 (41641417.0, 'ATL', 1993),
 (49383513.0, 'ATL', 1994),
 (47235445.0, 'ATL', 1995),
 (49698500.0, 'ATL

```
Answer: 
[(31135472.0, 'ANA', 1997),
 (41281000.0, 'ANA', 1998),
 (55388166.0, 'ANA', 1999),
 (51464167.0, 'ANA', 2000),
 (47535167.0, 'ANA', 2001),
 (61721667.0, 'ANA', 2002),
 (79031667.0, 'ANA', 2003),
 (100534667.0, 'ANA', 2004),
 (32347000.0, 'ARI', 1998),
 (68703999.0, 'ARI', 1999),
 (81027833.0, 'ARI', 2000),
 (85082999.0, 'ARI', 2001),
 (102819999.0, 'ARI', 2002),
 (80657000.0, 'ARI', 2003),
 (69780750.0, 'ARI', 2004),
 (62329166.0, 'ARI', 2005),
 (59684226.0, 'ARI', 2006),
 (52067546.0, 'ARI', 2007),
 (66202712.0, 'ARI', 2008),
 (73115666.0, 'ARI', 2009),
 (60718166.0, 'ARI', 2010),
 (53639833.0, 'ARI', 2011),
 (73804833.0, 'ARI', 2012),
 (90132000.0, 'ARI', 2013),
 (14807000.0, 'ATL', 1985),
 (17102786.0, 'ATL', 1986),
 (16544560.0, 'ATL', 1987),
 (12728174.0, 'ATL', 1988),
 (11112334.0, 'ATL', 1989),
 (14555501.0, 'ATL', 1990),
 (18403500.0, 'ATL', 1991),
 (34625333.0, 'ATL', 1992),
 (41641417.0, 'ATL', 1993),
 (49383513.0, 'ATL', 1994),
 (47235445.0, 'ATL', 1995),
 (49698500.0, 'ATL', 1996),
 (52278500.0, 'ATL', 1997),
 (61186000.0, 'ATL', 1998),
 (73140000.0, 'ATL', 1999),
 (84537836.0, 'ATL', 2000),
 (91936166.0, 'ATL', 2001),
 (92870367.0, 'ATL', 2002),
 (106243667.0, 'ATL', 2003),
 (90182500.0, 'ATL', 2004),
 (86457302.0, 'ATL', 2005),
 (90156876.0, 'ATL', 2006),
 (87290833.0, 'ATL', 2007),
 (102365683.0, 'ATL', 2008),
 (96726166.0, 'ATL', 2009),
 (84423666.0, 'ATL', 2010),
 (87002692.0, 'ATL', 2011),
 (82829942.0, 'ATL', 2012),
 (87871525.0, 'ATL', 2013),
 (11560712.0, 'BAL', 1985),
 (13001258.0, 'BAL', 1986),
 (13900273.0, 'BAL', 1987),
 (13532075.0, 'BAL', 1988),
 (8275167.0, 'BAL', 1989),
 (9680084.0, 'BAL', 1990),
 (17519000.0, 'BAL', 1991),
 (23780667.0, 'BAL', 1992),
 (29096500.0, 'BAL', 1993),
 (38849769.0, 'BAL', 1994),
 (43942521.0, 'BAL', 1995),
 (54490315.0, 'BAL', 1996),
 (58516400.0, 'BAL', 1997),
 (72355634.0, 'BAL', 1998),
 (80605863.0, 'BAL', 1999),
 (81447435.0, 'BAL', 2000),
 (67599540.0, 'BAL', 2001),
 (60493487.0, 'BAL', 2002),
 (73877500.0, 'BAL', 2003),
 (51623333.0, 'BAL', 2004),
 (73914333.0, 'BAL', 2005),
 (72585582.0, 'BAL', 2006),
 (93174808.0, 'BAL', 2007),
 (67196246.0, 'BAL', 2008),
 (67101666.0, 'BAL', 2009),
 (81612500.0, 'BAL', 2010),
 (85304038.0, 'BAL', 2011),
 (77353999.0, 'BAL', 2012),
 (84393333.0, 'BAL', 2013),
 (10897560.0, 'BOS', 1985),
 (14402239.0, 'BOS', 1986),
 (10144167.0, 'BOS', 1987),
 (13896092.0, 'BOS', 1988),
 (17481748.0, 'BOS', 1989),
 (20558333.0, 'BOS', 1990),
 (35167500.0, 'BOS', 1991),
 (43610584.0, 'BOS', 1992),
 (37120583.0, 'BOS', 1993),
 (37859084.0, 'BOS', 1994),
 (32455518.0, 'BOS', 1995),
 (42393500.0, 'BOS', 1996),
 (43558750.0, 'BOS', 1997),
 (56757000.0, 'BOS', 1998),
 (63497500.0, 'BOS', 1999),
 (77940333.0, 'BOS', 2000),
 (110035833.0, 'BOS', 2001),
 (108366060.0, 'BOS', 2002),
 (99946500.0, 'BOS', 2003),
 (127298500.0, 'BOS', 2004),
 (123505125.0, 'BOS', 2005),
 (120099824.0, 'BOS', 2006),
 (143026214.0, 'BOS', 2007),
 (133390035.0, 'BOS', 2008),
 (121345999.0, 'BOS', 2009),
 (162447333.0, 'BOS', 2010),
 (161762475.0, 'BOS', 2011),
 (173186617.0, 'BOS', 2012),
 (151530000.0, 'BOS', 2013),
 (14427894.0, 'CAL', 1985),
 (14427258.0, 'CAL', 1986),
 (12843499.0, 'CAL', 1987),
 (11947388.0, 'CAL', 1988),
 (15097833.0, 'CAL', 1989),
 (21720000.0, 'CAL', 1990),
 (33060001.0, 'CAL', 1991),
 (34749334.0, 'CAL', 1992),
 (28588334.0, 'CAL', 1993),
 (25156218.0, 'CAL', 1994),
 (31223171.0, 'CAL', 1995),
 (28738000.0, 'CAL', 1996),
 (9846178.0, 'CHA', 1985),
 (10418819.0, 'CHA', 1986),
 (10641843.0, 'CHA', 1987),
 (6390000.0, 'CHA', 1988),
 (7265410.0, 'CHA', 1989),
 (9491500.0, 'CHA', 1990),
 (16919667.0, 'CHA', 1991),
 (30160833.0, 'CHA', 1992),
 (39696166.0, 'CHA', 1993),
 (39183836.0, 'CHA', 1994),
 (46961282.0, 'CHA', 1995),
 (45139500.0, 'CHA', 1996),
 (57740000.0, 'CHA', 1997),
 (38335000.0, 'CHA', 1998),
 (25620000.0, 'CHA', 1999),
 (31133500.0, 'CHA', 2000),
 (65653667.0, 'CHA', 2001),
 (57052833.0, 'CHA', 2002),
 (51010000.0, 'CHA', 2003),
 (65212500.0, 'CHA', 2004),
 (75178000.0, 'CHA', 2005),
 (102750667.0, 'CHA', 2006),
 (108671833.0, 'CHA', 2007),
 (121189332.0, 'CHA', 2008),
 (96068500.0, 'CHA', 2009),
 (105530000.0, 'CHA', 2010),
 (127789000.0, 'CHA', 2011),
 (96919500.0, 'CHA', 2012),
 (120065277.0, 'CHA', 2013),
 (12702917.0, 'CHN', 1985),
 (17208165.0, 'CHN', 1986),
 (14307999.0, 'CHN', 1987),
 (13119198.0, 'CHN', 1988),
 (10668000.0, 'CHN', 1989),
 (13624000.0, 'CHN', 1990),
 (23175667.0, 'CHN', 1991),
 (29829686.0, 'CHN', 1992),
 (39386666.0, 'CHN', 1993),
 (36287333.0, 'CHN', 1994),
 (29505834.0, 'CHN', 1995),
 (33081000.0, 'CHN', 1996),
 (42155333.0, 'CHN', 1997),
 (50838000.0, 'CHN', 1998),
 (62343000.0, 'CHN', 1999),
 (60539333.0, 'CHN', 2000),
 (64715833.0, 'CHN', 2001),
 (75690833.0, 'CHN', 2002),
 (79868333.0, 'CHN', 2003),
 (90560000.0, 'CHN', 2004),
 (87032933.0, 'CHN', 2005),
 (94424499.0, 'CHN', 2006),
 (99670332.0, 'CHN', 2007),
 (118345833.0, 'CHN', 2008),
 (134809000.0, 'CHN', 2009),
 (146609000.0, 'CHN', 2010),
 (125047329.0, 'CHN', 2011),
 (88197033.0, 'CHN', 2012),
 (100567726.0, 'CHN', 2013),
 (8359917.0, 'CIN', 1985),
 (11906388.0, 'CIN', 1986),
 (9281500.0, 'CIN', 1987),
 (8888409.0, 'CIN', 1988),
 (11072000.0, 'CIN', 1989),
 (14370000.0, 'CIN', 1990),
 (26305333.0, 'CIN', 1991),
 (35931499.0, 'CIN', 1992),
 (44879666.0, 'CIN', 1993),
 (40961833.0, 'CIN', 1994),
 (43144670.0, 'CIN', 1995),
 (42526334.0, 'CIN', 1996),
 (49768000.0, 'CIN', 1997),
 (23005000.0, 'CIN', 1998),
 (33962761.0, 'CIN', 1999),
 (46867200.0, 'CIN', 2000),
 (48986000.0, 'CIN', 2001),
 (45050390.0, 'CIN', 2002),
 (59355667.0, 'CIN', 2003),
 (46615250.0, 'CIN', 2004),
 (61892583.0, 'CIN', 2005),
 (60909519.0, 'CIN', 2006),
 (68524980.0, 'CIN', 2007),
 (74117695.0, 'CIN', 2008),
 (73558500.0, 'CIN', 2009),
 (71761542.0, 'CIN', 2010),
 (75947134.0, 'CIN', 2011),
 (82203616.0, 'CIN', 2012),
 (106404462.0, 'CIN', 2013),
 (6551666.0, 'CLE', 1985),
 (7809500.0, 'CLE', 1986),
 (8513750.0, 'CLE', 1987),
 (8936500.0, 'CLE', 1988),
 (9094500.0, 'CLE', 1989),
 (14487000.0, 'CLE', 1990),
 (17635000.0, 'CLE', 1991),
 (9373044.0, 'CLE', 1992),
 (18561000.0, 'CLE', 1993),
 (30490500.0, 'CLE', 1994),
 (37937835.0, 'CLE', 1995),
 (48107360.0, 'CLE', 1996),
 (56802460.0, 'CLE', 1997),
 (60800166.0, 'CLE', 1998),
 (72978462.0, 'CLE', 1999),
 (75880771.0, 'CLE', 2000),
 (93152001.0, 'CLE', 2001),
 (78909449.0, 'CLE', 2002),
 (48584834.0, 'CLE', 2003),
 (34319300.0, 'CLE', 2004),
 (41502500.0, 'CLE', 2005),
 (56031500.0, 'CLE', 2006),
 (61673267.0, 'CLE', 2007),
 (78970066.0, 'CLE', 2008),
 (81579166.0, 'CLE', 2009),
 (61203966.0, 'CLE', 2010),
 (48776566.0, 'CLE', 2011),
 (78430300.0, 'CLE', 2012),
 (75771800.0, 'CLE', 2013),
 (10353500.0, 'COL', 1993),
 (23887333.0, 'COL', 1994),
 (34154717.0, 'COL', 1995),
 (40179823.0, 'COL', 1996),
 (43559667.0, 'COL', 1997),
 (50484648.0, 'COL', 1998),
 (61935837.0, 'COL', 1999),
 (61111190.0, 'COL', 2000),
 (71541334.0, 'COL', 2001),
 (56851043.0, 'COL', 2002),
 (67179667.0, 'COL', 2003),
 (65445167.0, 'COL', 2004),
 (47839000.0, 'COL', 2005),
 (41233000.0, 'COL', 2006),
 (54041000.0, 'COL', 2007),
 (68655500.0, 'COL', 2008),
 (75201000.0, 'COL', 2009),
 (84227000.0, 'COL', 2010),
 (88148071.0, 'COL', 2011),
 (78069571.0, 'COL', 2012),
 (74409071.0, 'COL', 2013),
 (10348143.0, 'DET', 1985),
 (12335714.0, 'DET', 1986),
 (12122881.0, 'DET', 1987),
 (12869571.0, 'DET', 1988),
 (15146404.0, 'DET', 1989),
 (17593238.0, 'DET', 1990),
 (23838333.0, 'DET', 1991),
 (27322834.0, 'DET', 1992),
 (38150165.0, 'DET', 1993),
 (41446501.0, 'DET', 1994),
 (37044168.0, 'DET', 1995),
 (23438000.0, 'DET', 1996),
 (17272000.0, 'DET', 1997),
 (24065000.0, 'DET', 1998),
 (36489666.0, 'DET', 1999),
 (58265167.0, 'DET', 2000),
 (53416167.0, 'DET', 2001),
 (55048000.0, 'DET', 2002),
 (49168000.0, 'DET', 2003),
 (46832000.0, 'DET', 2004),
 (69092000.0, 'DET', 2005),
 (82612866.0, 'DET', 2006),
 (94800369.0, 'DET', 2007),
 (137685196.0, 'DET', 2008),
 (115085145.0, 'DET', 2009),
 (122864928.0, 'DET', 2010),
 (105700231.0, 'DET', 2011),
 (132300000.0, 'DET', 2012),
 (145989500.0, 'DET', 2013),
 (19330545.0, 'FLO', 1993),
 (21633000.0, 'FLO', 1994),
 (24515781.0, 'FLO', 1995),
 (31022500.0, 'FLO', 1996),
 (48692500.0, 'FLO', 1997),
 (41322667.0, 'FLO', 1998),
 (21085000.0, 'FLO', 1999),
 (19872000.0, 'FLO', 2000),
 (35762500.0, 'FLO', 2001),
 (41979917.0, 'FLO', 2002),
 (49450000.0, 'FLO', 2003),
 (42143042.0, 'FLO', 2004),
 (60408834.0, 'FLO', 2005),
 (14671500.0, 'FLO', 2006),
 (30507000.0, 'FLO', 2007),
 (21811500.0, 'FLO', 2008),
 (36834000.0, 'FLO', 2009),
 (57029719.0, 'FLO', 2010),
 (56944000.0, 'FLO', 2011),
 (9993051.0, 'HOU', 1985),
 (9873276.0, 'HOU', 1986),
 (12608371.0, 'HOU', 1987),
 (12286167.0, 'HOU', 1988),
 (15029500.0, 'HOU', 1989),
 (18330000.0, 'HOU', 1990),
 (12852500.0, 'HOU', 1991),
 (15407500.0, 'HOU', 1992),
 (30210500.0, 'HOU', 1993),
 (33126000.0, 'HOU', 1994),
 (34169834.0, 'HOU', 1995),
 (28487000.0, 'HOU', 1996),
 (34777500.0, 'HOU', 1997),
 (42374000.0, 'HOU', 1998),
 (54914000.0, 'HOU', 1999),
 (51289111.0, 'HOU', 2000),
 (60612667.0, 'HOU', 2001),
 (63448417.0, 'HOU', 2002),
 (71040000.0, 'HOU', 2003),
 (75397000.0, 'HOU', 2004),
 (76779000.0, 'HOU', 2005),
 (88694435.0, 'HOU', 2006),
 (87759000.0, 'HOU', 2007),
 (88930414.0, 'HOU', 2008),
 (102996414.0, 'HOU', 2009),
 (92355500.0, 'HOU', 2010),
 (70694000.0, 'HOU', 2011),
 (60651000.0, 'HOU', 2012),
 (17890700.0, 'HOU', 2013),
 (9321179.0, 'KCA', 1985),
 (13043698.0, 'KCA', 1986),
 (11828056.0, 'KCA', 1987),
 (14556562.0, 'KCA', 1988),
 (18683568.0, 'KCA', 1989),
 (23361084.0, 'KCA', 1990),
 (26319834.0, 'KCA', 1991),
 (33893834.0, 'KCA', 1992),
 (41346167.0, 'KCA', 1993),
 (40541334.0, 'KCA', 1994),
 (29532834.0, 'KCA', 1995),
 (20281250.0, 'KCA', 1996),
 (34655000.0, 'KCA', 1997),
 (36862500.0, 'KCA', 1998),
 (26225000.0, 'KCA', 1999),
 (23433000.0, 'KCA', 2000),
 (35422500.0, 'KCA', 2001),
 (47257000.0, 'KCA', 2002),
 (40518000.0, 'KCA', 2003),
 (47609000.0, 'KCA', 2004),
 (36881000.0, 'KCA', 2005),
 (47294000.0, 'KCA', 2006),
 (67116500.0, 'KCA', 2007),
 (58245500.0, 'KCA', 2008),
 (70519333.0, 'KCA', 2009),
 (71405210.0, 'KCA', 2010),
 (35712000.0, 'KCA', 2011),
 (60916225.0, 'KCA', 2012),
 (80091725.0, 'KCA', 2013),
 (94867822.0, 'LAA', 2005),
 (103472000.0, 'LAA', 2006),
 (109251333.0, 'LAA', 2007),
 (119216333.0, 'LAA', 2008),
 (113709000.0, 'LAA', 2009),
 (104963866.0, 'LAA', 2010),
 (138543166.0, 'LAA', 2011),
 (154485166.0, 'LAA', 2012),
 (124174750.0, 'LAA', 2013),
 (10967917.0, 'LAN', 1985),
 (14913776.0, 'LAN', 1986),
 (13675403.0, 'LAN', 1987),
 (16850515.0, 'LAN', 1988),
 (21071562.0, 'LAN', 1989),
 (21318704.0, 'LAN', 1990),
 (32790664.0, 'LAN', 1991),
 (44788166.0, 'LAN', 1992),
 (39331999.0, 'LAN', 1993),
 (38000001.0, 'LAN', 1994),
 (39273201.0, 'LAN', 1995),
 (35355000.0, 'LAN', 1996),
 (45380304.0, 'LAN', 1997),
 (48820000.0, 'LAN', 1998),
 (80862453.0, 'LAN', 1999),
 (87924286.0, 'LAN', 2000),
 (109105953.0, 'LAN', 2001),
 (94850953.0, 'LAN', 2002),
 (105572620.0, 'LAN', 2003),
 (92902001.0, 'LAN', 2004),
 (83039000.0, 'LAN', 2005),
 (98447187.0, 'LAN', 2006),
 (108454524.0, 'LAN', 2007),
 (118588536.0, 'LAN', 2008),
 (100414592.0, 'LAN', 2009),
 (95358016.0, 'LAN', 2010),
 (104188999.0, 'LAN', 2011),
 (95143575.0, 'LAN', 2012),
 (223362196.0, 'LAN', 2013),
 (118078000.0, 'MIA', 2012),
 (33601900.0, 'MIA', 2013),
 (33914904.0, 'MIL', 1998),
 (43377395.0, 'MIL', 1999),
 (36505333.0, 'MIL', 2000),
 (43886833.0, 'MIL', 2001),
 (50287833.0, 'MIL', 2002),
 (40627000.0, 'MIL', 2003),
 (27528500.0, 'MIL', 2004),
 (39934833.0, 'MIL', 2005),
 (57568333.0, 'MIL', 2006),
 (70986500.0, 'MIL', 2007),
 (80937499.0, 'MIL', 2008),
 (80182502.0, 'MIL', 2009),
 (81108278.0, 'MIL', 2010),
 (85497333.0, 'MIL', 2011),
 (97653944.0, 'MIL', 2012),
 (76947033.0, 'MIL', 2013),
 (5764821.0, 'MIN', 1985),
 (8748167.0, 'MIN', 1986),
 (6397500.0, 'MIN', 1987),
 (12462666.0, 'MIN', 1988),
 (15531666.0, 'MIN', 1989),
 (14602000.0, 'MIN', 1990),
 (23361833.0, 'MIN', 1991),
 (28027834.0, 'MIN', 1992),
 (28217933.0, 'MIN', 1993),
 (28438500.0, 'MIN', 1994),
 (25410500.0, 'MIN', 1995),
 (23117000.0, 'MIN', 1996),
 (34072500.0, 'MIN', 1997),
 (27927500.0, 'MIN', 1998),
 (21257500.0, 'MIN', 1999),
 (16519500.0, 'MIN', 2000),
 (24130000.0, 'MIN', 2001),
 (40425000.0, 'MIN', 2002),
 (55505000.0, 'MIN', 2003),
 (53585000.0, 'MIN', 2004),
 (56186000.0, 'MIN', 2005),
 (63396006.0, 'MIN', 2006),
 (71439500.0, 'MIN', 2007),
 (56932766.0, 'MIN', 2008),
 (65299266.0, 'MIN', 2009),
 (97559166.0, 'MIN', 2010),
 (112737000.0, 'MIN', 2011),
 (94085000.0, 'MIN', 2012),
 (75337500.0, 'MIN', 2013),
 (11284107.0, 'ML4', 1985),
 (9943642.0, 'ML4', 1986),
 (7293224.0, 'ML4', 1987),
 (8402000.0, 'ML4', 1988),
 (11533000.0, 'ML4', 1989),
 (19719167.0, 'ML4', 1990),
 (23115500.0, 'ML4', 1991),
 (31013667.0, 'ML4', 1992),
 (23806834.0, 'ML4', 1993),
 (24350500.0, 'ML4', 1994),
 (17798825.0, 'ML4', 1995),
 (21730000.0, 'ML4', 1996),
 (23655338.0, 'ML4', 1997),
 (9470166.0, 'MON', 1985),
 (11103600.0, 'MON', 1986),
 (6942052.0, 'MON', 1987),
 (9603333.0, 'MON', 1988),
 (13807389.0, 'MON', 1989),
 (16586388.0, 'MON', 1990),
 (10732333.0, 'MON', 1991),
 (15822334.0, 'MON', 1992),
 (18899333.0, 'MON', 1993),
 (19098000.0, 'MON', 1994),
 (12364000.0, 'MON', 1995),
 (16264500.0, 'MON', 1996),
 (19295500.0, 'MON', 1997),
 (10641500.0, 'MON', 1998),
 (17903000.0, 'MON', 1999),
 (32994333.0, 'MON', 2000),
 (35159500.0, 'MON', 2001),
 (38670500.0, 'MON', 2002),
 (51948500.0, 'MON', 2003),
 (40897500.0, 'MON', 2004),
 (14238204.0, 'NYA', 1985),
 (18494253.0, 'NYA', 1986),
 (17099714.0, 'NYA', 1987),
 (19441152.0, 'NYA', 1988),
 (17114375.0, 'NYA', 1989),
 (20912318.0, 'NYA', 1990),
 (27344168.0, 'NYA', 1991),
 (37543334.0, 'NYA', 1992),
 (42624900.0, 'NYA', 1993),
 (45731334.0, 'NYA', 1994),
 (48874851.0, 'NYA', 1995),
 (54191792.0, 'NYA', 1996),
 (62241545.0, 'NYA', 1997),
 (66806867.0, 'NYA', 1998),
 (86734359.0, 'NYA', 1999),
 (92338260.0, 'NYA', 2000),
 (112287143.0, 'NYA', 2001),
 (125928583.0, 'NYA', 2002),
 (152749814.0, 'NYA', 2003),
 (184193950.0, 'NYA', 2004),
 (208306817.0, 'NYA', 2005),
 (194663079.0, 'NYA', 2006),
 (189259045.0, 'NYA', 2007),
 (207896789.0, 'NYA', 2008),
 (201449189.0, 'NYA', 2009),
 (206333389.0, 'NYA', 2010),
 (202275028.0, 'NYA', 2011),
 (196522289.0, 'NYA', 2012),
 (231978886.0, 'NYA', 2013),
 (10834762.0, 'NYN', 1985),
 (15393714.0, 'NYN', 1986),
 (13846714.0, 'NYN', 1987),
 (15269314.0, 'NYN', 1988),
 (19885071.0, 'NYN', 1989),
 (21722834.0, 'NYN', 1990),
 (32590001.0, 'NYN', 1991),
 (44602002.0, 'NYN', 1992),
 (39043667.0, 'NYN', 1993),
 (30956583.0, 'NYN', 1994),
 (27674992.0, 'NYN', 1995),
 (24479500.0, 'NYN', 1996),
 (39800400.0, 'NYN', 1997),
 (52077999.0, 'NYN', 1998),
 (65092092.0, 'NYN', 1999),
 (79509776.0, 'NYN', 2000),
 (93174428.0, 'NYN', 2001),
 (94633593.0, 'NYN', 2002),
 (116876429.0, 'NYN', 2003),
 (96660970.0, 'NYN', 2004),
 (101305821.0, 'NYN', 2005),
 (101084963.0, 'NYN', 2006),
 (115231663.0, 'NYN', 2007),
 (137793376.0, 'NYN', 2008),
 (149373987.0, 'NYN', 2009),
 (134422942.0, 'NYN', 2010),
 (118847309.0, 'NYN', 2011),
 (93353983.0, 'NYN', 2012),
 (49448346.0, 'NYN', 2013),
 (9058606.0, 'OAK', 1985),
 (9779421.0, 'OAK', 1986),
 (11680839.0, 'OAK', 1987),
 (9690000.0, 'OAK', 1988),
 (15613070.0, 'OAK', 1989),
 (19887501.0, 'OAK', 1990),
 (36999167.0, 'OAK', 1991),
 (41035000.0, 'OAK', 1992),
 (37812333.0, 'OAK', 1993),
 (34172500.0, 'OAK', 1994),
 (37739225.0, 'OAK', 1995),
 (21243000.0, 'OAK', 1996),
 (24018500.0, 'OAK', 1997),
 (21303000.0, 'OAK', 1998),
 (24431833.0, 'OAK', 1999),
 (31971333.0, 'OAK', 2000),
 (33810750.0, 'OAK', 2001),
 (40004167.0, 'OAK', 2002),
 (50260834.0, 'OAK', 2003),
 (59425667.0, 'OAK', 2004),
 (55425762.0, 'OAK', 2005),
 (62243079.0, 'OAK', 2006),
 (79366940.0, 'OAK', 2007),
 (47967126.0, 'OAK', 2008),
 (61910000.0, 'OAK', 2009),
 (55254900.0, 'OAK', 2010),
 (66536500.0, 'OAK', 2011),
 (55372500.0, 'OAK', 2012),
 (60132500.0, 'OAK', 2013),
 (10124966.0, 'PHI', 1985),
 (11590166.0, 'PHI', 1986),
 (11514233.0, 'PHI', 1987),
 (13838000.0, 'PHI', 1988),
 (10604000.0, 'PHI', 1989),
 (13173667.0, 'PHI', 1990),
 (22487332.0, 'PHI', 1991),
 (24383834.0, 'PHI', 1992),
 (28538334.0, 'PHI', 1993),
 (31599000.0, 'PHI', 1994),
 (30555945.0, 'PHI', 1995),
 (34314500.0, 'PHI', 1996),
 (36656500.0, 'PHI', 1997),
 (36297500.0, 'PHI', 1998),
 (31692500.0, 'PHI', 1999),
 (47308000.0, 'PHI', 2000),
 (41663833.0, 'PHI', 2001),
 (57954999.0, 'PHI', 2002),
 (70780000.0, 'PHI', 2003),
 (92919167.0, 'PHI', 2004),
 (95522000.0, 'PHI', 2005),
 (88273333.0, 'PHI', 2006),
 (89428213.0, 'PHI', 2007),
 (97879880.0, 'PHI', 2008),
 (113004046.0, 'PHI', 2009),
 (141928379.0, 'PHI', 2010),
 (172976379.0, 'PHI', 2011),
 (174538938.0, 'PHI', 2012),
 (169863189.0, 'PHI', 2013),
 (9227500.0, 'PIT', 1985),
 (10843500.0, 'PIT', 1986),
 (7652000.0, 'PIT', 1987),
 (5998500.0, 'PIT', 1988),
 (12737500.0, 'PIT', 1989),
 (15556000.0, 'PIT', 1990),
 (23634667.0, 'PIT', 1991),
 (33944167.0, 'PIT', 1992),
 (24822467.0, 'PIT', 1993),
 (24217250.0, 'PIT', 1994),
 (18355345.0, 'PIT', 1995),
 (23017500.0, 'PIT', 1996),
 (10771667.0, 'PIT', 1997),
 (15065000.0, 'PIT', 1998),
 (24697666.0, 'PIT', 1999),
 (28928334.0, 'PIT', 2000),
 (57760833.0, 'PIT', 2001),
 (42323599.0, 'PIT', 2002),
 (54812429.0, 'PIT', 2003),
 (32227929.0, 'PIT', 2004),
 (38133000.0, 'PIT', 2005),
 (46717750.0, 'PIT', 2006),
 (38537833.0, 'PIT', 2007),
 (48689783.0, 'PIT', 2008),
 (48693000.0, 'PIT', 2009),
 (34943000.0, 'PIT', 2010),
 (45047000.0, 'PIT', 2011),
 (62951999.0, 'PIT', 2012),
 (77062000.0, 'PIT', 2013),
 (11036583.0, 'SDN', 1985),
 (11380693.0, 'SDN', 1986),
 (11065796.0, 'SDN', 1987),
 (9561002.0, 'SDN', 1988),
 (14195000.0, 'SDN', 1989),
 (17588334.0, 'SDN', 1990),
 (22150001.0, 'SDN', 1991),
 (26854167.0, 'SDN', 1992),
 (25511333.0, 'SDN', 1993),
 (14916333.0, 'SDN', 1994),
 (26382334.0, 'SDN', 1995),
 (28348172.0, 'SDN', 1996),
 (37363672.0, 'SDN', 1997),
 (46861500.0, 'SDN', 1998),
 (49768179.0, 'SDN', 1999),
 (54821000.0, 'SDN', 2000),
 (39182833.0, 'SDN', 2001),
 (41425000.0, 'SDN', 2002),
 (45210000.0, 'SDN', 2003),
 (55384833.0, 'SDN', 2004),
 (63290833.0, 'SDN', 2005),
 (69896141.0, 'SDN', 2006),
 (58110567.0, 'SDN', 2007),
 (73677616.0, 'SDN', 2008),
 (43333700.0, 'SDN', 2009),
 (37799300.0, 'SDN', 2010),
 (45869140.0, 'SDN', 2011),
 (55244700.0, 'SDN', 2012),
 (65585500.0, 'SDN', 2013),
 (4613000.0, 'SEA', 1985),
 (5958309.0, 'SEA', 1986),
 (2263500.0, 'SEA', 1987),
 (7342450.0, 'SEA', 1988),
 (9779500.0, 'SEA', 1989),
 (12553667.0, 'SEA', 1990),
 (15691833.0, 'SEA', 1991),
 (23179833.0, 'SEA', 1992),
 (32696333.0, 'SEA', 1993),
 (29228500.0, 'SEA', 1994),
 (36481311.0, 'SEA', 1995),
 (41328501.0, 'SEA', 1996),
 (41540661.0, 'SEA', 1997),
 (54087036.0, 'SEA', 1998),
 (54125003.0, 'SEA', 1999),
 (58915000.0, 'SEA', 2000),
 (74720834.0, 'SEA', 2001),
 (80282668.0, 'SEA', 2002),
 (86959167.0, 'SEA', 2003),
 (81515834.0, 'SEA', 2004),
 (87754334.0, 'SEA', 2005),
 (87959833.0, 'SEA', 2006),
 (106460833.0, 'SEA', 2007),
 (117666482.0, 'SEA', 2008),
 (98904166.0, 'SEA', 2009),
 (86510000.0, 'SEA', 2010),
 (86110600.0, 'SEA', 2011),
 (81978100.0, 'SEA', 2012),
 (74005043.0, 'SEA', 2013),
 (8221714.0, 'SFN', 1985),
 (8947000.0, 'SFN', 1986),
 (7290000.0, 'SFN', 1987),
 (12380000.0, 'SFN', 1988),
 (14962834.0, 'SFN', 1989),
 (19335333.0, 'SFN', 1990),
 (30967666.0, 'SFN', 1991),
 (33163168.0, 'SFN', 1992),
 (35050000.0, 'SFN', 1993),
 (42638666.0, 'SFN', 1994),
 (36462777.0, 'SFN', 1995),
 (37144725.0, 'SFN', 1996),
 (35592378.0, 'SFN', 1997),
 (42565834.0, 'SFN', 1998),
 (46595057.0, 'SFN', 1999),
 (53737826.0, 'SFN', 2000),
 (63280167.0, 'SFN', 2001),
 (78299835.0, 'SFN', 2002),
 (82852167.0, 'SFN', 2003),
 (82019166.0, 'SFN', 2004),
 (90199500.0, 'SFN', 2005),
 (90056419.0, 'SFN', 2006),
 (90219056.0, 'SFN', 2007),
 (76594500.0, 'SFN', 2008),
 (83026450.0, 'SFN', 2009),
 (98641333.0, 'SFN', 2010),
 (118198333.0, 'SFN', 2011),
 (117620683.0, 'SFN', 2012),
 (140180334.0, 'SFN', 2013),
 (11817083.0, 'SLN', 1985),
 (9875010.0, 'SLN', 1986),
 (11758000.0, 'SLN', 1987),
 (12880000.0, 'SLN', 1988),
 (16078833.0, 'SLN', 1989),
 (20523334.0, 'SLN', 1990),
 (21860001.0, 'SLN', 1991),
 (27583836.0, 'SLN', 1992),
 (23367334.0, 'SLN', 1993),
 (29275601.0, 'SLN', 1994),
 (37101000.0, 'SLN', 1995),
 (40269667.0, 'SLN', 1996),
 (45456667.0, 'SLN', 1997),
 (54672521.0, 'SLN', 1998),
 (49778195.0, 'SLN', 1999),
 (61453863.0, 'SLN', 2000),
 (78538333.0, 'SLN', 2001),
 (74660875.0, 'SLN', 2002),
 (83786666.0, 'SLN', 2003),
 (83228333.0, 'SLN', 2004),
 (92106833.0, 'SLN', 2005),
 (88891371.0, 'SLN', 2006),
 (90286823.0, 'SLN', 2007),
 (99624449.0, 'SLN', 2008),
 (88528409.0, 'SLN', 2009),
 (93540751.0, 'SLN', 2010),
 (105433572.0, 'SLN', 2011),
 (110300862.0, 'SLN', 2012),
 (92260110.0, 'SLN', 2013),
 (27280000.0, 'TBA', 1998),
 (38870000.0, 'TBA', 1999),
 (62765129.0, 'TBA', 2000),
 (56980000.0, 'TBA', 2001),
 (34380000.0, 'TBA', 2002),
 (19630000.0, 'TBA', 2003),
 (29556667.0, 'TBA', 2004),
 (29679067.0, 'TBA', 2005),
 (34917967.0, 'TBA', 2006),
 (24123500.0, 'TBA', 2007),
 (43820597.0, 'TBA', 2008),
 (63313034.0, 'TBA', 2009),
 (71923471.0, 'TBA', 2010),
 (41053571.0, 'TBA', 2011),
 (64173500.0, 'TBA', 2012),
 (52955272.0, 'TBA', 2013),
 (7676500.0, 'TEX', 1985),
 (6743119.0, 'TEX', 1986),
 (880000.0, 'TEX', 1987),
 (5342131.0, 'TEX', 1988),
 (11893781.0, 'TEX', 1989),
 (14874372.0, 'TEX', 1990),
 (18224500.0, 'TEX', 1991),
 (30128167.0, 'TEX', 1992),
 (36376959.0, 'TEX', 1993),
 (32973597.0, 'TEX', 1994),
 (34581451.0, 'TEX', 1995),
 (39041528.0, 'TEX', 1996),
 (53448838.0, 'TEX', 1997),
 (56572095.0, 'TEX', 1998),
 (76709931.0, 'TEX', 1999),
 (70795921.0, 'TEX', 2000),
 (88633500.0, 'TEX', 2001),
 (105526122.0, 'TEX', 2002),
 (103491667.0, 'TEX', 2003),
 (55050417.0, 'TEX', 2004),
 (55849000.0, 'TEX', 2005),
 (68228662.0, 'TEX', 2006),
 (68318675.0, 'TEX', 2007),
 (67712326.0, 'TEX', 2008),
 (68178798.0, 'TEX', 2009),
 (55250544.0, 'TEX', 2010),
 (92299264.0, 'TEX', 2011),
 (120510974.0, 'TEX', 2012),
 (112522600.0, 'TEX', 2013),
 (8812550.0, 'TOR', 1985),
 (12611047.0, 'TOR', 1986),
 (10479501.0, 'TOR', 1987),
 (12241225.0, 'TOR', 1988),
 (16261666.0, 'TOR', 1989),
 (17756834.0, 'TOR', 1990),
 (19902417.0, 'TOR', 1991),
 (44788666.0, 'TOR', 1992),
 (47279166.0, 'TOR', 1993),
 (43433668.0, 'TOR', 1994),
 (50590000.0, 'TOR', 1995),
 (29555083.0, 'TOR', 1996),
 (47079833.0, 'TOR', 1997),
 (51376000.0, 'TOR', 1998),
 (45444333.0, 'TOR', 1999),
 (44838332.0, 'TOR', 2000),
 (76895999.0, 'TOR', 2001),
 (76864333.0, 'TOR', 2002),
 (51269000.0, 'TOR', 2003),
 (50017000.0, 'TOR', 2004),
 (45719500.0, 'TOR', 2005),
 (71365000.0, 'TOR', 2006),
 (81942800.0, 'TOR', 2007),
 (97793900.0, 'TOR', 2008),
 (80538300.0, 'TOR', 2009),
 (62234000.0, 'TOR', 2010),
 (62567800.0, 'TOR', 2011),
 (75009200.0, 'TOR', 2012),
 (126288100.0, 'TOR', 2013),
 (48581500.0, 'WAS', 2005),
 (63143000.0, 'WAS', 2006),
 (36947500.0, 'WAS', 2007),
 (54961000.0, 'WAS', 2008),
 (59928000.0, 'WAS', 2009),
 (61400000.0, 'WAS', 2010),
 (63856928.0, 'WAS', 2011),
 (80855143.0, 'WAS', 2012),
 (113703270.0, 'WAS', 2013)]
    
```

In [4]:
query = """
rollback;
SELECT salary
FROM salaries
WHERE teamid='LAN' AND yearid=1987;
"""
cursor.execute(query)
cursor.fetchall()

[(225000.0,),
 (150000.0,),
 (1520000.0,),
 (65000.0,),
 (62500.0,),
 (165000.0,),
 (300000.0,),
 (800000.0,),
 (62500.0,),
 (65000.0,),
 (805000.0,),
 (737500.0,),
 (170000.0,),
 (850000.0,),
 (670000.0,),
 (265000.0,),
 (731250.0,),
 (280000.0,),
 (1100000.0,),
 (875000.0,),
 (62500.0,),
 (144000.0,),
 (370153.0,),
 (1850000.0,),
 (837500.0,),
 (100000.0,),
 (62500.0,),
 (350000.0,)]

# What is the first and last year played for each player? *Hint:* Create a new table from 'Fielding.csv'.
    

```
We only created 3 tables from CSV files during AWS setup, so we have to create the rest of the tables in the baseball database 


Copy below into terminal window to see the csv files (from: https://stackoverflow.com/questions/1875305/command-line-csv-viewer/44021782)
1. (base) ubuntu@ip-172-31-21-131:~$ \ls
Anaconda3-2019.07-Linux-x86_64.sh  anaconda3	 lahman-csv_2014-02-14.zip    site_database.sql
Untitled.ipynb			   baseballdata  lahman-csv_2014-02-14.zip.1
2. (base) ubuntu@ip-172-31-21-131:~$ cd baseballdata
3. (base) ubuntu@ip-172-31-21-131:~/baseballdata$ column -s, -t < Fielding.csv #this is how to view CSV file!
playerID   yearID  stint  teamID  lgID  POS  G    GS    InnOuts  PO    A    E    DP   PB  WP   SB   CS  ZR
ansonca01  1871    1      RC1     NA    1B   1    7     0        0     0    
biermch01  1871    1      FW1     NA    1B   1    9     0        2     0    
carleji01  1871    1      CL1     NA    1B   29   295   4        34    10   
connone01  1871    1      TRO     NA    1B   4    35    1        5     1    
cravebi01  1871    1      TRO     NA    1B   2    18    1        1     1    
fishech01  1871    1      RC1     NA    1B   2    12    0        1     0    
fislewe01  1871    1      PH1     NA    1B   26   240   1        7     9    
flynncl01  1871    1      TRO     NA    1B   19   183   8        9     12   

4. cd ..
5. psql
6. \connect baseball
7. After entering psql and connect to baseball, copy/paste below into command line: 
        CREATE TABLE IF NOT EXISTS Fielding 
        (playerID varchar(20) NOT NULL,
	    yearID int NOT NULL,
	    stint int NOT NULL,
	    teamID text DEFAULT NULL,
	    lgID text DEFAULT NULL,
	    POS varchar(20) DEFAULT NULL,
	    G int NOT NULL, 
        GS int DEFAULT NULL,
        InnOuts int DEFAULT NULL,
        PO int DEFAULT NULL,
        A int DEFAULT NULL,
        E int DEFAULT NULL,
        DP int DEFAULT NULL,
        PB int DEFAULT NULL,
        WP int DEFAULT NULL,
        SB int DEFAULT NULL,
        CS int DEFAULT NULL,
        ZR int DEFAULT NULL
 
          );

8. (Still connected to baseball) Copy/paste the following into the command line: 
        COPY Fielding FROM '/home/ubuntu/baseballdata/Fielding.csv' DELIMITER ',' CSV HEADER;

For errors:
ALTER TABLE FIELDING ALTER COLUMN GS int DEFAULT NULL; #didn't work
DROP TABLE FIELDING; 
```

In [5]:
#LIMIT and ORDER BY were not specified in the question--so I did not set a limit and chose my own order
query = """
rollback;
SELECT playerID, MIN(yearID), MAX(yearID)
FROM fielding
GROUP BY playerID
ORDER BY MAX(yearID)-MIN(yearID) DESC;
"""
cursor.execute(query)
cursor.fetchall()

[('orourji01', 1872, 1904),
 ('altroni01', 1898, 1929),
 ('lathaar01', 1880, 1909),
 ('mcguide01', 1884, 1912),
 ('eversjo01', 1902, 1929),
 ('streega01', 1904, 1931),
 ('ryanno01', 1966, 1993),
 ('jennihu01', 1891, 1918),
 ('minosmi01', 1949, 1976),
 ('ansonca01', 1871, 1897),
 ('johnto01', 1963, 1989),
 ('moyerja01', 1986, 2012),
 ('francju01', 1982, 2007),
 ('broutda01', 1879, 1904),
 ('quinnja01', 1909, 1933),
 ('newsobo01', 1929, 1953),
 ('gleaski01', 1888, 1912),
 ('fiskca01', 1969, 1993),
 ('henderi01', 1979, 2003),
 ('morgami01', 1978, 2002),
 ('oroscje01', 1979, 2003),
 ('ryanja01', 1889, 1913),
 ('kaatji01', 1959, 1983),
 ('houghch01', 1970, 1994),
 ('wallabo01', 1894, 1918),
 ('wynnea01', 1939, 1963),
 ('hartlgr01', 1911, 1934),
 ('niekrph01', 1964, 1987),
 ('ruffire01', 1924, 1947),
 ('spahnwa01', 1942, 1965),
 ('griffcl01', 1891, 1914),
 ('coonejo01', 1921, 1944),
 ('cobbty01', 1905, 1928),
 ('lyonste01', 1923, 1946),
 ('dempsri01', 1969, 1992),
 ('schrepa01', 1922, 1945),

```
Answer:
[('orourji01', 1872, 1904),
 ('altroni01', 1898, 1929),
 ('lathaar01', 1880, 1909),
 ('mcguide01', 1884, 1912),
 ('eversjo01', 1902, 1929),
 ('streega01', 1904, 1931),
 ('ryanno01', 1966, 1993),
 ('jennihu01', 1891, 1918),
 ('minosmi01', 1949, 1976),
 ('ansonca01', 1871, 1897),
 ('johnto01', 1963, 1989),
 ('moyerja01', 1986, 2012),
 ('francju01', 1982, 2007),
 ('broutda01', 1879, 1904),
 ('quinnja01', 1909, 1933),
 ('newsobo01', 1929, 1953),
 ('gleaski01', 1888, 1912),
 ('fiskca01', 1969, 1993),
 ('henderi01', 1979, 2003),
 ('morgami01', 1978, 2002),
 ('oroscje01', 1979, 2003),
 ('ryanja01', 1889, 1913),
 ('kaatji01', 1959, 1983),
 ('houghch01', 1970, 1994),
 ('wallabo01', 1894, 1918),
 ('wynnea01', 1939, 1963),
 ('hartlgr01', 1911, 1934),
 ('niekrph01', 1964, 1987),
 ('ruffire01', 1924, 1947),
 ('spahnwa01', 1942, 1965),
 ('griffcl01', 1891, 1914),
 ('coonejo01', 1921, 1944),
 ('cobbty01', 1905, 1928),
 ('lyonste01', 1923, 1946),
 ('dempsri01', 1969, 1992),
 ('schrepa01', 1922, 1945),
 ('eckerde01', 1975, 1998),
 ('oconnja01', 1887, 1910),
 ('vizquom01', 1989, 2012),
 ('clemero02', 1984, 2007),
 ('maranra01', 1912, 1935),
 ('carltst01', 1965, 1988),
 ('rosepe01', 1963, 1986),
 ('musiast01', 1941, 1963),
 ('robinbr01', 1955, 1977),
 ('nuxhajo01', 1944, 1966),
 ('pennohe01', 1912, 1934),
 ('gossari01', 1972, 1994),
 ('winfida01', 1973, 1995),
 ('suttodo01', 1966, 1988),
 ('hornsro01', 1915, 1937),
 ('martide01', 1976, 1998),
 ('collied01', 1906, 1928),
 ('staubru01', 1963, 1985),
 ('aaronha01', 1954, 1976),
 ('raineti01', 1980, 2002),
 ('maddugr01', 1986, 2008),
 ('blylebe01', 1970, 1992),
 ('perezto01', 1964, 1986),
 ('mayswi01', 1951, 1973),
 ('bushgu01', 1923, 1945),
 ('yastrca01', 1961, 1983),
 ('bendech01', 1903, 1925),
 ('speaktr01', 1907, 1928),
 ('phillda01', 1941, 1962),
 ('ruthba01', 1914, 1935),
 ('sewellu01', 1921, 1942),
 ('baineha01', 1980, 2001),
 ('rixeyep01', 1912, 1933),
 ('mccovwi01', 1959, 1980),
 ('thompsa01', 1885, 1906),
 ('slaugen01', 1938, 1959),
 ('niekrjo01', 1967, 1988),
 ('bondsba01', 1986, 2007),
 ('morgajo02', 1963, 1984),
 ('reussje01', 1969, 1990),
 ('jonessa01', 1914, 1935),
 ('dykesji01', 1918, 1939),
 ('mccarti01', 1959, 1980),
 ('glavito02', 1987, 2008),
 ('griffke02', 1989, 2010),
 ('sheffga01', 1988, 2009),
 ('thomeji01', 1991, 2012),
 ('francjo01', 1984, 2005),
 ('killeha01', 1954, 1975),
 ('valoel01', 1940, 1961),
 ('perryga01', 1962, 1983),
 ('peitzhe01', 1892, 1913),
 ('johnsra05', 1988, 2009),
 ('cavarph01', 1934, 1955),
 ('smoltjo01', 1988, 2009),
 ('clarkfr01', 1894, 1915),
 ('willite01', 1939, 1960),
 ('gordoto01', 1988, 2009),
 ('mitchcl01', 1911, 1932),
 ('kalinal01', 1953, 1974),
 ('youngcy01', 1890, 1911),
 ('beckbo01', 1924, 1945),
 ('luquedo01', 1914, 1935),
 ('davisha01', 1895, 1915),
 ('simmote01', 1968, 1988),
 ('mesajo01', 1987, 2007),
 ('dahlebi01', 1891, 1911),
 ('nettlgr01', 1968, 1988),
 ('bucknbi01', 1970, 1990),
 ('fairlro01', 1958, 1978),
 ('foxxji01', 1925, 1945),
 ('molitpa01', 1978, 1998),
 ('vanceda01', 1915, 1935),
 ('stargwi01', 1962, 1982),
 ('brettge01', 1973, 1993),
 ('simmoal01', 1924, 1944),
 ('grimmch01', 1916, 1936),
 ('mcdanli01', 1955, 1975),
 ('evansda01', 1969, 1989),
 ('carisfr01', 1903, 1923),
 ('caldwea01', 1928, 1948),
 ('mclisca01', 1944, 1964),
 ('tananfr01', 1973, 1993),
 ('applilu01', 1930, 1950),
 ('hoytwa01', 1918, 1938),
 ('ofarrbo01', 1915, 1935),
 ('lajoina01', 1896, 1916),
 ('wagneho01', 1897, 1917),
 ('jacksre01', 1967, 1987),
 ('leachto01', 1898, 1918),
 ('honeyri01', 1977, 1997),
 ('darwida01', 1978, 1998),
 ('robinfr02', 1956, 1976),
 ('sierrru01', 1986, 2006),
 ('fellebo01', 1936, 1956),
 ('vernomi01', 1939, 1959),
 ('batismi01', 1992, 2012),
 ('johnswa01', 1907, 1927),
 ('murraed02', 1977, 1997),
 ('donovbi01', 1898, 1918),
 ('rhodear01', 1991, 2011),
 ('crossla01', 1887, 1907),
 ('wilheho01', 1952, 1972),
 ('hodgegi01', 1943, 1963),
 ('oliveda02', 1993, 2013),
 ('rodriiv01', 1991, 2011),
 ('gowdyha01', 1910, 1930),
 ('leonadu02', 1933, 1953),
 ('ottme01', 1926, 1946),
 ('ripkeca01', 1981, 2001),
 ('austiji01', 1909, 1929),
 ('wellsda01', 1987, 2007),
 ('gonzami01', 1912, 1932),
 ('adamsba01', 1906, 1926),
 ('mulhote01', 1986, 2006),
 ('dicksmu01', 1939, 1959),
 ('dawsoan01', 1976, 1996),
 ('simmocu01', 1947, 1967),
 ('blackle01', 1910, 1929),
 ('anderla02', 1975, 1994),
 ('sugdejo01', 1893, 1912),
 ('mcgratu01', 1965, 1984),
 ('stiebda01', 1979, 1998),
 ('brownke01', 1986, 2005),
 ('orourfr01', 1912, 1931),
 ('zimmech01', 1884, 1903),
 ('cronijo01', 1926, 1945),
 ('judgejo01', 1915, 1934),
 ('waltebu01', 1931, 1950),
 ('rodrial01', 1994, 2013),
 ('piercbi02', 1945, 1964),
 ('merckke01', 1989, 2008),
 ('jonesfi01', 1896, 1915),
 ('davisge01', 1890, 1909),
 ('stairma01', 1992, 2011),
 ('hemslro01', 1928, 1947),
 ('cramedo01', 1929, 1948),
 ('reuscri01', 1972, 1991),
 ('schilcu01', 1988, 2007),
 ('johnssi01', 1928, 1947),
 ('palmera01', 1986, 2005),
 ('hermaba01', 1926, 1945),
 ('burdoja01', 1872, 1891),
 ('joosted01', 1936, 1955),
 ('yountro01', 1974, 1993),
 ('galaran01', 1985, 2004),
 ('kressre01', 1927, 1946),
 ('evansdw01', 1972, 1991),
 ('hinespa01', 1872, 1891),
 ('woodlge01', 1943, 1962),
 ('ruelmu01', 1915, 1934),
 ('garbege01', 1969, 1988),
 ('careyma01', 1910, 1929),
 ('haineje01', 1918, 1937),
 ('biggicr01', 1988, 2007),
 ('halldi01', 1952, 1971),
 ('seaneru01', 1989, 2008),
 ('mcbrige01', 1901, 1920),
 ('whitede01', 1871, 1890),
 ('trammal01', 1977, 1996),
 ('haywora01', 1926, 1945),
 ('bartedi01', 1927, 1946),
 ('palmeji01', 1965, 1984),
 ('gwynnto01', 1982, 2001),
 ('downibr01', 1973, 1992),
 ('scheifr01', 1887, 1906),
 ('hartnga01', 1922, 1941),
 ('jonesch06', 1993, 2012),
 ('stanaos01', 1906, 1925),
 ('lopezal01', 1928, 1947),
 ('alexape01', 1911, 1930),
 ('gaettga01', 1981, 2000),
 ('daviswi02', 1960, 1979),
 ('hardeme01', 1928, 1947),
 ('berrayo01', 1946, 1965),
 ('seaveto01', 1967, 1986),
 ('winegra01', 1930, 1949),
 ('faberre01', 1914, 1933),
 ('callani01', 1894, 1913),
 ('campabe01', 1964, 1983),
 ('heganji01', 1941, 1960),
 ('santibe01', 1986, 2005),
 ('dalyto01', 1884, 1903),
 ('mcraeha01', 1968, 1987),
 ('wakefti01', 1992, 2011),
 ('becklja01', 1888, 1907),
 ('merklfr01', 1907, 1926),
 ('rogerke01', 1989, 2008),
 ('battijo01', 1871, 1890),
 ('ricesa01', 1915, 1934),
 ('kennebo01', 1939, 1957),
 ('heilmha01', 1914, 1932),
 ('myersgr01', 1987, 2005),
 ('johnssy01', 1922, 1940),
 ('hamnegr01', 1944, 1962),
 ('thomafr04', 1990, 2008),
 ('elybo01', 1884, 1902),
 ('mcinnst01', 1909, 1927),
 ('aloumo01', 1990, 2008),
 ('gehrich01', 1924, 1942),
 ('griffke01', 1973, 1991),
 ('bressru01', 1914, 1932),
 ('groteje01', 1963, 1981),
 ('zachato01', 1918, 1936),
 ('pettian01', 1995, 2013),
 ('grimebu01', 1916, 1934),
 ('bankser01', 1953, 1971),
 ('parkeda01', 1973, 1991),
 ('bakerdu01', 1968, 1986),
 ('johnsja01', 1966, 1984),
 ('koosmje01', 1967, 1985),
 ('baylodo01', 1970, 1988),
 ('cruzjo01', 1970, 1988),
 ('wanerll01', 1927, 1945),
 ('mclemma01', 1986, 2004),
 ('cartega01', 1974, 1992),
 ('whitalo01', 1977, 1995),
 ('klinero01', 1952, 1970),
 ('mcgrifr01', 1986, 2004),
 ('wanerpa01', 1926, 1944),
 ('sosasa01', 1989, 2007),
 ('yosted01', 1944, 1962),
 ('sauerha01', 1941, 1959),
 ('sutclri01', 1976, 1994),
 ('roushed01', 1913, 1931),
 ('stantmi02', 1989, 2007),
 ('hudliwi01', 1926, 1944),
 ('jenkife01', 1965, 1983),
 ('foxne01', 1947, 1965),
 ('crawfsa01', 1899, 1917),
 ('ryanji01', 1885, 1903),
 ('wilheka01', 1903, 1921),
 ('sprinru01', 1992, 2010),
 ('fernato01', 1983, 2001),
 ('davisch01', 1981, 1999),
 ('seiboso01', 1915, 1933),
 ('carewro01', 1967, 1985),
 ('weathda01', 1991, 2009),
 ('jacksmi02', 1986, 2004),
 ('sukefcl01', 1927, 1945),
 ('riddljo02', 1930, 1948),
 ('applepe01', 1927, 1945),
 ('normafr01', 1962, 1980),
 ('nelsoca01', 1872, 1890),
 ('rootch01', 1923, 1941),
 ('candejo01', 1975, 1993),
 ('turnete01', 1901, 1919),
 ('jonesdo01', 1982, 2000),
 ('surhobj01', 1987, 2005),
 ('roberro01', 1948, 1966),
 ('schanwa01', 1913, 1931),
 ('snydepo01', 1873, 1891),
 ('smithoz01', 1978, 1996),
 ('troutdi01', 1939, 1957),
 ('parrila02', 1977, 1995),
 ('osteecl01', 1957, 1975),
 ('mayru01', 1965, 1983),
 ('murcebo01', 1965, 1983),
 ('bresnro01', 1897, 1915),
 ('lisenho01', 1927, 1945),
 ('gerhajo01', 1873, 1891),
 ('ferreri01', 1929, 1947),
 ('reedro01', 1966, 1984),
 ('speiech01', 1971, 1989),
 ('dickebi01', 1928, 1946),
 ('mondari01', 1966, 1984),
 ('howeldi01', 1940, 1958),
 ('cuellmi01', 1959, 1977),
 ('wilsowi02', 1976, 1994),
 ('leiteal01', 1987, 2005),
 ('mcclubo01', 1975, 1993),
 ('gonzalu01', 1990, 2008),
 ('jeterde01', 1995, 2013),
 ('bentoal01', 1934, 1952),
 ('larkiba01', 1986, 2004),
 ('sandesc01', 1978, 1996),
 ('friscfr01', 1919, 1937),
 ('riverma01', 1995, 2013),
 ('tiantlu01', 1964, 1982),
 ('foremfr01', 1884, 1902),
 ('coffmdi01', 1927, 1945),
 ('alexado01', 1971, 1989),
 ('herriar01', 1929, 1947),
 ('wiseri01', 1964, 1982),
 ('fitzsfr01', 1925, 1943),
 ('keelewi01', 1892, 1910),
 ('finlest01', 1989, 2007),
 ('wheatza01', 1909, 1927),
 ('reesepe01', 1940, 1958),
 ('tayloto02', 1958, 1976),
 ('conceda01', 1970, 1988),
 ('boonebo01', 1972, 1990),
 ('walkedi02', 1931, 1949),
 ('willicy01', 1912, 1930),
 ('rijojo01', 1984, 2002),
 ('wingoiv01', 1911, 1929),
 ('brocklo01', 1961, 1979),
 ('hawkila01', 1995, 2013),
 ('alomasa02', 1989, 2007),
 ('schofdi01', 1953, 1971),
 ('brocado01', 1992, 2009),
 ('picinva01', 1916, 1933),
 ('farredu01', 1888, 1905),
 ('grimsja01', 1989, 2006),
 ('fostege01', 1969, 1986),
 ('deandi01', 1930, 1947),
 ('burdele01', 1950, 1967),
 ('aparilu01', 1956, 1973),
 ('piersji01', 1950, 1967),
 ('schalra01', 1912, 1929),
 ('blakesh01', 1920, 1937),
 ('donovpa01', 1890, 1907),
 ('duffyhu01', 1888, 1905),
 ('mizejo01', 1936, 1953),
 ('harrato01', 1969, 1986),
 ('saberbr01', 1984, 2001),
 ('torremi01', 1967, 1984),
 ('lemonbo01', 1941, 1958),
 ('hamptmi01', 1993, 2010),
 ('sullibi03', 1899, 1916),
 ('bluegos01', 1922, 1939),
 ('isrinja01', 1995, 2012),
 ('suppaje01', 1995, 2012),
 ('cardejo02', 1963, 1980),
 ('rudoldi01', 1910, 1927),
 ('truckvi01', 1941, 1958),
 ('hershor01', 1983, 2000),
 ('burksel01', 1987, 2004),
 ('otisam01', 1967, 1984),
 ('durocle01', 1928, 1945),
 ('coninje01', 1990, 2007),
 ('martipe02', 1992, 2009),
 ('whitefr01', 1973, 1990),
 ('pascuca02', 1954, 1971),
 ('suttoez01', 1871, 1888),
 ('cuyleki01', 1921, 1938),
 ('ibanera01', 1996, 2013),
 ('pacioto01', 1970, 1987),
 ('jamiech01', 1915, 1932),
 ('mussimi01', 1991, 2008),
 ('smithle02', 1980, 1997),
 ('uhlege01', 1919, 1936),
 ('ramirma02', 1993, 2010),
 ('beniqju01', 1971, 1988),
 ('harrile01', 1988, 2005),
 ('fregoji01', 1961, 1978),
 ('oliveal01', 1968, 1985),
 ('sadecra01', 1960, 1977),
 ('connoro01', 1880, 1897),
 ('boggswa01', 1982, 1999),
 ('kraneed01', 1962, 1979),
 ('mastewa02', 1939, 1956),
 ('valenfe01', 1980, 1997),
 ('bluevi01', 1969, 1986),
 ('penaor01', 1958, 1975),
 ('vizcajo01', 1989, 2006),
 ('mcmahdo02', 1957, 1974),
 ('dunstsh01', 1985, 2002),
 ('woodwi01', 1961, 1978),
 ('motama01', 1962, 1979),
 ('jacklfr01', 1900, 1917),
 ('phillto02', 1982, 1999),
 ('kellejo01', 1891, 1908),
 ('russebi01', 1969, 1986),
 ('paigesa01', 1948, 1965),
 ('tanneje01', 1894, 1911),
 ('burgesm01', 1949, 1966),
 ('millebo04', 1957, 1974),
 ('damonjo01', 1995, 2012),
 ('johnsfr01', 1922, 1939),
 ('corcoto01', 1890, 1907),
 ('fordwh01', 1950, 1967),
 ('fingero01', 1968, 1985),
 ('crandde01', 1949, 1966),
 ('morrija02', 1977, 1994),
 ('schmimi01', 1972, 1989),
 ('nichobi01', 1936, 1953),
 ('timlimi01', 1991, 2008),
 ('daviser01', 1984, 2001),
 ('hendrge01', 1971, 1988),
 ('watsobo01', 1967, 1984),
 ('hoffmtr01', 1993, 2010),
 ('ausmubr01', 1993, 2010),
 ('wilsoji01', 1923, 1940),
 ('sewelri01', 1932, 1949),
 ('clemero01', 1955, 1972),
 ('coneda01', 1986, 2003),
 ('mancugu01', 1928, 1945),
 ('martibu01', 1969, 1986),
 ('macfada01', 1926, 1943),
 ('schoere01', 1945, 1962),
 ('mcphebi01', 1882, 1899),
 ('maulal01', 1884, 1901),
 ('davissp01', 1928, 1945),
 ('bellbu01', 1972, 1989),
 ('seymocy01', 1896, 1913),
 ('bellja01', 1986, 2003),
 ('byerlbu01', 1943, 1960),
 ('hortowi01', 1963, 1980),
 ('doakbi01', 1912, 1929),
 ('lowebo01', 1890, 1907),
 ('ewingbu01', 1880, 1897),
 ('owenmi01', 1937, 1954),
 ('edmonji01', 1993, 2010),
 ('snidedu01', 1947, 1964),
 ('jonesda01', 1901, 1918),
 ('schaege01', 1901, 1918),
 ('touchcl01', 1928, 1945),
 ('frymawo01', 1966, 1983),
 ('traynpi01', 1920, 1937),
 ('plesada01', 1986, 2003),
 ('quirkja01', 1975, 1992),
 ('bordepa01', 1988, 2005),
 ('abernte02', 1955, 1972),
 ('javiest01', 1984, 2001),
 ('bergmda01', 1975, 1992),
 ('marquru01', 1908, 1925),
 ('stewada01', 1978, 1995),
 ('lollash01', 1946, 1963),
 ('gosligo01', 1921, 1938),
 ('jorgemi01', 1968, 1985),
 ('davalvi01', 1963, 1980),
 ('griffal01', 1976, 1993),
 ('henrybi01', 1952, 1969),
 ('wrighja01', 1996, 2013),
 ('embreal01', 1992, 2009),
 ('ceronri01', 1975, 1992),
 ('clarkja01', 1975, 1992),
 ('robinbi02', 1966, 1983),
 ('giambja01', 1995, 2012),
 ('davisma01', 1980, 1997),
 ('willibi01', 1959, 1976),
 ('peckiro01', 1910, 1927),
 ('lawve01', 1950, 1967),
 ('penato01', 1980, 1997),
 ('mcgeewi01', 1982, 1999),
 ('sheame01', 1927, 1944),
 ('jacksgr01', 1965, 1982),
 ('dwyerji01', 1973, 1990),
 ('randowi01', 1975, 1992),
 ('murphda05', 1976, 1993),
 ('garvest01', 1970, 1987),
 ('hargrbu01', 1913, 1930),
 ('martied01', 1987, 2004),
 ('kellyge01', 1915, 1932),
 ('galvipu01', 1875, 1892),
 ('mantlmi01', 1951, 1968),
 ('pizarju01', 1957, 1974),
 ('cromawa01', 1974, 1991),
 ('flanami01', 1975, 1992),
 ('tennefr02', 1894, 1911),
 ('klippjo01', 1950, 1967),
 ('coopewa01', 1940, 1957),
 ('pinsova01', 1958, 1975),
 ('belanma01', 1965, 1982),
 ('oneilst01', 1911, 1928),
 ('quinnjo02', 1884, 1901),
 ('covelst01', 1912, 1928),
 ('guarded01', 1993, 2009),
 ('shaffor01', 1874, 1890),
 ('anderga01', 1994, 2010),
 ('hernaro01', 1991, 2007),
 ('blanche01', 1997, 2013),
 ('boutoji01', 1962, 1978),
 ('webbsk01', 1932, 1948),
 ('blairpa01', 1964, 1980),
 ('kentje01', 1992, 2008),
 ('desauge01', 1930, 1946),
 ('aloufe01', 1958, 1974),
 ('kuheljo01', 1930, 1946),
 ('burkejo03', 1987, 2003),
 ('grovele01', 1925, 1941),
 ('reedje02', 1984, 2000),
 ('hairsje01', 1973, 1989),
 ('bailebo01', 1962, 1978),
 ('servisc01', 1988, 2004),
 ('smithlo01', 1978, 1994),
 ('bridgto01', 1930, 1946),
 ('camermi01', 1995, 2011),
 ('sandbry01', 1981, 1997),
 ('herbera01', 1950, 1966),
 ('jonesan01', 1996, 2012),
 ('cashno01', 1958, 1974),
 ('montawi01', 1966, 1982),
 ('downial01', 1961, 1977),
 ('posadjo01', 1995, 2011),
 ('cedence01', 1970, 1986),
 ('gumpera01', 1936, 1952),
 ('bellira01', 1982, 1998),
 ('hernake01', 1974, 1990),
 ('southbi01', 1913, 1929),
 ('pafkoan01', 1943, 1959),
 ('doyleja01', 1889, 1905),
 ('cormirh01', 1991, 2007),
 ('cansejo01', 1985, 2001),
 ('kleinch01', 1928, 1944),
 ('johnsde01', 1960, 1976),
 ('hebneri01', 1969, 1985),
 ('lowede01', 1997, 2013),
 ('bushjo01', 1912, 1928),
 ('mazerbi01', 1956, 1972),
 ('sullibi04', 1931, 1947),
 ('alvarwi01', 1989, 2005),
 ('welchbo01', 1978, 1994),
 ('goodedw01', 1984, 2000),
 ('grossgr01', 1973, 1989),
 ('gardnla01', 1908, 1924),
 ('gamblos01', 1969, 1985),
 ('gromest01', 1941, 1957),
 ('bunniji01', 1955, 1971),
 ('heltoto01', 1997, 2013),
 ('cepedor01', 1958, 1974),
 ('finlech01', 1986, 2002),
 ('ricede01', 1945, 1961),
 ('sandere02', 1991, 2007),
 ('abreubo01', 1996, 2012),
 ('jurgebi01', 1931, 1947),
 ('matheed01', 1952, 1968),
 ('wardjo01', 1878, 1894),
 ('grissma02', 1989, 2005),
 ('swindgr01', 1986, 2002),
 ('freembu01', 1891, 1907),
 ('crosefr01', 1932, 1948),
 ('roofph01', 1961, 1977),
 ('ortizda01', 1997, 2013),
 ('ridzist01', 1950, 1966),
 ('perryji01', 1959, 1975),
 ('loftoke01', 1991, 2007),
 ('higgipi01', 1930, 1946),
 ('bahnsst01', 1966, 1982),
 ('moseswa01', 1935, 1951),
 ('wyattwh01', 1929, 1945),
 ('powelbo01', 1961, 1977),
 ('claytro01', 1991, 2007),
 ('carrch01', 1898, 1914),
 ('rodriau01', 1967, 1983),
 ('strawda01', 1983, 1999),
 ('cicerjo01', 1929, 1945),
 ('alouje01', 1963, 1979),
 ('sievero01', 1949, 1965),
 ('medwijo01', 1932, 1948),
 ('wallide01', 1975, 1991),
 ('smithsh01', 1911, 1927),
 ('rowesc01', 1933, 1949),
 ('davisto02', 1960, 1976),
 ('worthal01', 1953, 1969),
 ('brownju01', 1925, 1941),
 ('mathech01', 1900, 1916),
 ('hermabi01', 1931, 1947),
 ('harpebr01', 1979, 1995),
 ('butlebr01', 1981, 1997),
 ('mcculcl01', 1940, 1956),
 ('breweji01', 1960, 1976),
 ('gibsobo01', 1959, 1975),
 ('roepr01', 1938, 1954),
 ('strunam01', 1908, 1924),
 ('princto01', 1987, 2003),
 ('newhoha01', 1939, 1955),
 ('kittrma01', 1890, 1906),
 ('hernali01', 1996, 2012),
 ('bergmo01', 1923, 1939),
 ('parkch01', 1994, 2010),
 ('torrejo01', 1961, 1977),
 ('facero01', 1953, 1969),
 ('manushe01', 1923, 1939),
 ('grichbo01', 1970, 1986),
 ('wilcomi01', 1970, 1986),
 ('gantnji01', 1976, 1992),
 ('hammoch01', 1990, 2006),
 ('sheckji01', 1897, 1913),
 ('chapmbe01', 1930, 1946),
 ('pikeli01', 1871, 1887),
 ('glassja01', 1879, 1895),
 ('livinpa01', 1901, 1917),
 ('majesha01', 1939, 1955),
 ('counscr01', 1995, 2011),
 ('drabomo01', 1956, 1972),
 ('adcocjo01', 1950, 1966),
 ('easleda01', 1992, 2008),
 ('lynnfr01', 1974, 1990),
 ('perkicy01', 1915, 1931),
 ('tebbebi01', 1936, 1952),
 ('vanhage01', 1887, 1903),
 ('howest01', 1980, 1996),
 ('pinielo01', 1968, 1984),
 ('keenaji01', 1875, 1891),
 ('vaughar01', 1932, 1948),
 ('ericksc01', 1990, 2006),
 ('pappami01', 1957, 1973),
 ('nixonot01', 1983, 1999),
 ('snowjt01', 1992, 2008),
 ('cairomi01', 1996, 2012),
 ('robinwi01', 1886, 1902),
 ('vosbeed01', 1986, 2002),
 ('coopece01', 1971, 1987),
 ('hoopeha01', 1909, 1925),
 ('konerpa01', 1997, 2013),
 ('gehrilo01', 1923, 1939),
 ('oneilpa01', 1985, 2001),
 ('burgmto01', 1968, 1984),
 ('trillma01', 1973, 1989),
 ('clemeja01', 1884, 1900),
 ('wagnehe01', 1902, 1918),
 ('floydcl01', 1993, 2009),
 ('colonba01', 1997, 2013),
 ('millest01', 1952, 1968),
 ('crigelo01', 1896, 1912),
 ('olerujo01', 1989, 2005),
 ('kotsama01', 1997, 2013),
 ('gibsoki01', 1979, 1995),
 ('whitede03', 1985, 2001),
 ('brownto01', 1882, 1898),
 ('wertzvi01', 1947, 1963),
 ('nichoki01', 1890, 1906),
 ('candito01', 1983, 1999),
 ('porteda02', 1971, 1987),
 ('myattgl01', 1920, 1936),
 ('walkela01', 1989, 2005),
 ('alomaro01', 1988, 2004),
 ('willima04', 1987, 2003),
 ('ashbyal01', 1973, 1989),
 ('tiefebo01', 1952, 1968),
 ('wallati01', 1980, 1996),
 ('lombaer01', 1931, 1947),
 ('forscke01', 1970, 1986),
 ('boyercl02', 1955, 1971),
 ('tavarju01', 1993, 2009),
 ('eisenji01', 1982, 1998),
 ('myershy01', 1909, 1925),
 ('righeda01', 1979, 1995),
 ('bradlbi01', 1899, 1915),
 ('myerbu01', 1925, 1941),
 ('mogrige01', 1911, 1927),
 ('washicl01', 1974, 1990),
 ('chancfr01', 1898, 1914),
 ('smithre06', 1966, 1982),
 ('delgaca01', 1993, 2009),
 ('muellra01', 1935, 1951),
 ('rolensc01', 1996, 2012),
 ('podrejo01', 1953, 1969),
 ('shousbr01', 1993, 2009),
 ('whiteea01', 1923, 1939),
 ('amesre01', 1903, 1919),
 ('planked01', 1901, 1917),
 ('tejadmi01', 1997, 2013),
 ('elberki01', 1898, 1914),
 ('gonzaju03', 1989, 2005),
 ('benchjo01', 1967, 1983),
 ('lolicmi01', 1963, 1979),
 ('castrju01', 1995, 2011),
 ('mayle01', 1966, 1982),
 ('martipe01', 1928, 1944),
 ('etchean01', 1962, 1978),
 ('mathebo01', 1871, 1887),
 ('gantro01', 1987, 2003),
 ('reedri01', 1988, 2003),
 ('lopesda01', 1972, 1987),
 ('tekulke01', 1974, 1989),
 ('johnsji01', 1911, 1926),
 ('norrimi01', 1975, 1990),
 ('castivi02', 1991, 2006),
 ('velarra01', 1987, 2002),
 ('hartbi01', 1886, 1901),
 ('milancl01', 1907, 1922),
 ('onsloed01', 1912, 1927),
 ('mageesh01', 1904, 1919),
 ('rizzuph01', 1941, 1956),
 ('baergca01', 1990, 2005),
 ('rogelbi01', 1925, 1940),
 ('donovdi01', 1950, 1965),
 ('forscbo01', 1974, 1989),
 ('crossmo01', 1892, 1907),
 ('renteed01', 1996, 2011),
 ('dimagjo01', 1936, 1951),
 ('milletr02', 1996, 2011),
 ('westsa01', 1927, 1942),
 ('langsma01', 1984, 1999),
 ('odoulle01', 1919, 1934),
 ('hunteto01', 1998, 2013),
 ('cardele01', 1960, 1975),
 ('cuccito01', 1930, 1945),
 ('schmijo01', 1941, 1956),
 ('clarkni01', 1905, 1920),
 ('sweenmi01', 1995, 2010),
 ('whitter01', 1976, 1991),
 ('forceda01', 1871, 1886),
 ('snydefr01', 1912, 1927),
 ('lylesp01', 1967, 1982),
 ('galanau01', 1934, 1949),
 ('postwa01', 1949, 1964),
 ('joynewa01', 1986, 2001),
 ('carpech01', 1997, 2012),
 ('shantbo01', 1949, 1964),
 ('ramospe01', 1955, 1970),
 ('rhoderi01', 1974, 1989),
 ('mahayro01', 1995, 2010),
 ('bancrda01', 1915, 1930),
 ('heintke01', 1937, 1952),
 ('bennech01', 1878, 1893),
 ('bottoji01', 1922, 1937),
 ('burkeje01', 1890, 1905),
 ('leeth01', 1933, 1948),
 ('martiti02', 1990, 2005),
 ('beltrca01', 1998, 2013),
 ('giustda01', 1962, 1977),
 ('goodmbi01', 1947, 1962),
 ('maricju01', 1960, 1975),
 ('knowlda01', 1965, 1980),
 ('mcgowbe01', 1922, 1937),
 ('powelja01', 1897, 1912),
 ('hackst01', 1932, 1947),
 ('rudijo01', 1967, 1982),
 ('heldwo01', 1954, 1969),
 ('mintogr01', 1975, 1990),
 ('chenbr01', 1998, 2013),
 ('hogsech01', 1929, 1944),
 ('lowenjo01', 1970, 1985),
 ('murphda02', 1900, 1915),
 ('gomezch02', 1993, 2008),
 ('ramirar01', 1998, 2013),
 ('roystje01', 1973, 1988),
 ('grubbjo01', 1972, 1987),
 ('mcauldi01', 1960, 1975),
 ('valenjo03', 1992, 2007),
 ('callijo01', 1958, 1973),
 ('gumbeha01', 1935, 1950),
 ('hadlebu01', 1926, 1941),
 ('zaungr01', 1995, 2010),
 ('cartejo01', 1983, 1998),
 ('brownll01', 1925, 1940),
 ('cicoted01', 1905, 1920),
 ('remlimi01', 1991, 2006),
 ('leifile01', 1905, 1920),
 ('torresa01', 1993, 2008),
 ('mccormi03', 1956, 1971),
 ('bettshu01', 1920, 1935),
 ('polleho01', 1941, 1956),
 ('fettemi01', 1989, 2004),
 ('gurala01', 1970, 1985),
 ('fasseje01', 1991, 2006),
 ('lacyle01', 1972, 1987),
 ('kleskry01', 1992, 2007),
 ('sundbji01', 1974, 1989),
 ('mullira01', 1977, 1992),
 ('reardje01', 1979, 1994),
 ('polanpl01', 1998, 2013),
 ('collida02', 1975, 1990),
 ('rojasco01', 1962, 1977),
 ('gullibi01', 1979, 1994),
 ('mayja01', 1917, 1932),
 ('powelja03', 1930, 1945),
 ('gerbewa01', 1914, 1929),
 ('burroje01', 1970, 1985),
 ('templga01', 1976, 1991),
 ('hillejo01', 1965, 1980),
 ('raffeke01', 1939, 1954),
 ('mcgrajo01', 1891, 1906),
 ('dobsojo01', 1939, 1954),
 ('startjo01', 1871, 1886),
 ('hevinjo02', 1930, 1945),
 ('delahed01', 1888, 1903),
 ('jonesto02', 1993, 2008),
 ('moneydo01', 1968, 1983),
 ('byrdati01', 1998, 2013),
 ('bonilbo01', 1986, 2001),
 ('gracema01', 1988, 2003),
 ('muellhe01', 1920, 1935),
 ('oglivbe01', 1971, 1986),
 ('wickmbo01', 1992, 2007),
 ('grohhe01', 1912, 1927),
 ('tayloza02', 1920, 1935),
 ('aguilri01', 1985, 2000),
 ('hubbeca01', 1928, 1943),
 ('ontivst02', 1985, 2000),
 ('kellyki01', 1878, 1893),
 ('hallaro01', 1998, 2013),
 ('howarfr01', 1958, 1973),
 ('cartyri01', 1964, 1979),
 ('mcfared01', 1893, 1908),
 ('bushdo01', 1908, 1923),
 ('galehde01', 1934, 1949),
 ('smithel01', 1886, 1901),
 ('riceji01', 1974, 1989),
 ('longhe01', 1889, 1904),
 ('garneph01', 1973, 1988),
 ('josefe01', 1988, 2003),
 ('appieke01', 1989, 2004),
 ('robined01', 1942, 1957),
 ('forstte01', 1971, 1986),
 ('hendeke01', 1965, 1980),
 ('dietrbi01', 1933, 1948),
 ('pippwa01', 1913, 1928),
 ('fletcel01', 1934, 1949),
 ('hernajo01', 1991, 2006),
 ('trachst01', 1993, 2008),
 ('pfefffr01', 1882, 1897),
 ('hillca01', 1915, 1930),
 ('beltrad01', 1998, 2013),
 ('matthga01', 1972, 1987),
 ('lucasre01', 1923, 1938),
 ('hanseda01', 1990, 2005),
 ('eversho01', 1941, 1956),
 ('freehbi01', 1961, 1976),
 ('bailebi01', 1907, 1922),
 ('piazzmi01', 1992, 2007),
 ('fieldji01', 1883, 1898),
 ('magadda01', 1986, 2001),
 ('chaveer01', 1998, 2013),
 ('zeileto01', 1989, 2004),
 ('wagnebi02', 1995, 2010),
 ('derosma01', 1998, 2013),
 ('huttoto01', 1966, 1981),
 ('harrebu01', 1965, 1980),
 ('kreutch01', 1988, 2003),
 ('jonnabu01', 1920, 1935),
 ('oberkke01', 1977, 1992),
 ('lockmwh01', 1945, 1960),
 ('dempsry01', 1998, 2013),
 ('pierzaj01', 1998, 2013),
 ('martida01', 1986, 2001),
 ('bannifl01', 1977, 1992),
 ('hallmbi01', 1888, 1903),
 ('bentoru01', 1910, 1925),
 ('obriech01', 1985, 2000),
 ('kingmda01', 1971, 1986),
 ('brunege01', 1956, 1971),
 ('ortajo01', 1972, 1987),
 ('penaal01', 1981, 1996),
 ('harribi01', 1923, 1938),
 ('lampde01', 1977, 1992),
 ('foliti01', 1970, 1985),
 ('lemonch01', 1975, 1990),
 ('chambch01', 1971, 1986),
 ('millebi02', 1921, 1936),
 ('willibe02', 1991, 2006),
 ('offerjo01', 1990, 2005),
 ('slaugdo01', 1982, 1997),
 ('sislege01', 1915, 1930),
 ('walkeha01', 1940, 1955),
 ('aguirha01', 1955, 1970),
 ('wittbo01', 1986, 2001),
 ('warnelo01', 1930, 1945),
 ('slatoji01', 1971, 1986),
 ('millwke01', 1997, 2012),
 ('bushodo01', 1875, 1890),
 ('sommeru01', 1912, 1927),
 ('questjo01', 1871, 1886),
 ('lindsji01', 1922, 1937),
 ('burnsge02', 1914, 1929),
 ('guilloz01', 1985, 2000),
 ('laniema01', 1938, 1953),
 ('gonzaal02', 1998, 2013),
 ('groatdi01', 1952, 1967),
 ('darwibo01', 1962, 1977),
 ('finnelo01', 1931, 1946),
 ('fournja01', 1912, 1927),
 ('frienbo01', 1951, 1966),
 ('hairsje02', 1998, 2013),
 ('collish01', 1910, 1925),
 ('hallme01', 1981, 1996),
 ('kessido01', 1964, 1979),
 ('bowala01', 1970, 1985),
 ('lockwsk01', 1965, 1980),
 ('venturo01', 1989, 2004),
 ('freylo01', 1933, 1948),
 ('seguidi01', 1962, 1977),
 ('ehmkeho01', 1915, 1930),
 ('bandosa01', 1966, 1981),
 ('murphjo04', 1932, 1947),
 ('samueju01', 1983, 1998),
 ('kirkped01', 1962, 1977),
 ('mcmilro01', 1951, 1966),
 ('severha01', 1911, 1926),
 ('mcmulke01', 1962, 1977),
 ('schripo01', 1886, 1901),
 ('suscege01', 1929, 1944),
 ('ceyro01', 1972, 1987),
 ('schumha02', 1931, 1946),
 ('grudzma01', 1995, 2010),
 ('mcgwima01', 1986, 2001),
 ('mannle01', 1913, 1928),
 ('yeagest01', 1972, 1986),
 ('stanlmi01', 1964, 1978),
 ('wynnji01', 1963, 1977),
 ('durbich01', 1999, 2013),
 ('hansero02', 1958, 1972),
 ('younger01', 1992, 2006),
 ('moorech02', 1973, 1987),
 ('thornan01', 1973, 1987),
 ('thondi01', 1979, 1993),
 ('hunteca01', 1965, 1979),
 ('soriaal01', 1999, 2013),
 ('mccorfr01', 1934, 1948),
 ('hoeftbi01', 1952, 1966),
 ('nashbi01', 1884, 1898),
 ('coombja01', 1906, 1920),
 ('lewisbu01', 1935, 1949),
 ('donneji01', 1884, 1898),
 ('hasslan01', 1971, 1985),
 ('maniocl01', 1920, 1934),
 ('ashburi01', 1948, 1962),
 ('doerrbo01', 1937, 1951),
 ('shouncl01', 1935, 1949),
 ('williwo02', 1993, 2007),
 ('maldoca01', 1981, 1995),
 ('hudsosi01', 1940, 1954),
 ('tolanbo01', 1965, 1979),
 ('northro01', 1942, 1956),
 ('meadole01', 1915, 1929),
 ('seleaa01', 1993, 2007),
 ('burrira01', 1973, 1987),
 ('elsteke01', 1986, 2000),
 ('walkege02', 1931, 1945),
 ('lopezja01', 1992, 2006),
 ('jacksda03', 1985, 1999),
 ('daubeja01', 1910, 1924),
 ('almonbi01', 1974, 1988),
 ('reynocr01', 1975, 1989),
 ('percitr01', 1995, 2009),
 ('gibsofr01', 1913, 1927),
 ('johnsha01', 1925, 1939),
 ('greggve01', 1911, 1925),
 ('puhlte01', 1977, 1991),
 ('lansfca01', 1978, 1992),
 ('stalege01', 1947, 1961),
 ('lillyte01', 1999, 2013),
 ('nathajo01', 1999, 2013),
 ('varitja01', 1997, 2011),
 ('grosske01', 1983, 1997),
 ('barbest01', 1960, 1974),
 ('pavanca01', 1998, 2012),
 ('bassljo01', 1913, 1927),
 ('lummi01', 1967, 1981),
 ('ferrewe01', 1927, 1941),
 ('allendi01', 1963, 1977),
 ('greenha01', 1933, 1947),
 ('harrijo03', 1914, 1928),
 ('lonboji01', 1965, 1979),
 ('jacksda02', 1983, 1997),
 ('clarkto02', 1995, 2009),
 ('willije01', 1999, 2013),
 ('bairdo01', 1976, 1990),
 ('guerrvl01', 1996, 2010),
 ('anderjo01', 1894, 1908),
 ('thomafr03', 1951, 1965),
 ('ankieri01', 1999, 2013),
 ('fisheed02', 1959, 1973),
 ('yorkru01', 1934, 1948),
 ('martiti01', 1974, 1988),
 ('caseyhu01', 1935, 1949),
 ('maybejo01', 1968, 1982),
 ('thomsbo01', 1946, 1960),
 ('orsuljo01', 1983, 1997),
 ('nehfar01', 1915, 1929),
 ('milleri01', 1971, 1985),
 ('graneja01', 1908, 1922),
 ('villoro01', 1995, 2009),
 ('campbbi02', 1973, 1987),
 ('wellsve01', 1999, 2013),
 ('richapa01', 1932, 1946),
 ('palmede01', 1989, 2003),
 ('shortch02', 1959, 1973),
 ('boehlge01', 1912, 1926),
 ('portuma01', 1985, 1999),
 ...]
```

# Who has played the most all star games?

In [6]:
#View all columns in allstarfull 
inspector.get_columns('allstarfull')


[{'name': 'playerid',
  'type': VARCHAR(length=20),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'yearid',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'gamenum',
  'type': VARCHAR(length=20),
  'nullable': False,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'gameid',
  'type': VARCHAR(length=12),
  'nullable': True,
  'default': 'NULL::character varying',
  'autoincrement': False,
  'comment': None},
 {'name': 'teamid',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'lgid',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'gp',
  'type': VARCHAR(length=20),
  'nullable': True,
  'default': 'NULL::character varying',
  'autoincrement': False,
  'comment': None},
 {'name': 'startingpos',
  'type': VARCHAR(len

In [7]:
#By ordering the list descending and limiting the list to 1, my output is the player with the highest number of allstar games played
query = """
rollback;
SELECT playerID, COUNT(gameID) 
FROM allstarfull
GROUP BY playerID
ORDER BY COUNT(gameID) DESC
LIMIT 1;
"""
cursor.execute(query)
cursor.fetchall()

[('aaronha01', 25)]

```
Answer: aaronha01
```

# Which school has generated the most distinct players? *Hint:* Create new table from 'CollegePlaying.csv'.

```
OF NOTE: There was no CSV file called "CollegePlaying"--so I used the CSV that appeared to contain the most relevant information ("SchoolsPlayers")--which I have confirmed contain colleges and playerIDs in Step 1 below. 
1. View column examples in terminal window to help me create the table: 
ubuntu@ip-172-31-21-131:~/baseballdata$ column -s, -t < SchoolsPlayers.csv
playerID   schoolID     yearMin  yearMax
aardsda01  pennst       2001     2001
aardsda01  rice         2002     2003
abbeybe01  vermont      1888     1892
abbotgl01  carkansas    1970     1970
abbotje01  kentucky     1991     1992
abbotji01  michigan     1986     1988
abbotky01  longbeach    1989     1989
abbotky01  ucsd         1987     1988
abbotod01  washjeffpa   1906     1910
abernte01  elon         1939     1941
ablesha01  swesterntx   1903     1904
accarje01  illinoisst   2001     2003
ackerji01  texas        1978     1980
acrema01   nmstate      1989     1991
adairje01  okstate      1957     1958
adairji01  etxbaptist   1924     1927

2. psql
3. \connect baseball
4. Copy/paste:
        CREATE TABLE IF NOT EXISTS SchoolsPlayers 
        (playerID varchar(20) NOT NULL,
	    schoolID varchar(20) NOT NULL,
        yearMin int NOT NULL,
	    yearMax int NOT NULL
         );

5. Copy/paste:
        COPY SchoolsPlayers FROM '/home/ubuntu/baseballdata/SchoolsPlayers.csv' DELIMITER ',' CSV HEADER;
```

In [8]:
#By ordering the list descending and limiting the list to 1, my output is the school with the highest number of distinct players. 
query = """
rollback;
SELECT schoolID, COUNT(DISTINCT(playerID)) 
FROM SchoolsPlayers
GROUP BY schoolID
ORDER BY COUNT(DISTINCT(playerID)) DESC
LIMIT 1;
"""
cursor.execute(query)
cursor.fetchall()

[('usc', 102)]

```
Answer: USC
```

# Which players have the longest career? Assume that the `debut` and `finalGame` columns comprise the start and end, respectively, of a player's career. *Hint:* Create a new table from 'Master.csv'. Also note that strings can be converted to dates using the [`DATE`](https://wiki.postgresql.org/wiki/Working_with_Dates_and_Times_in_PostgreSQL#WORKING_with_DATETIME.2C_DATE.2C_and_INTERVAL_VALUES) function and can then be subtracted from each other yielding their difference in days.

In [ ]:
#DO NOT RUN THIS CELL. Markdown, even with the ```, makes the column examples below hard to read. 
1. View example columns in Master.CSV. In the 1st, 2nd, and 5th row, there are seemingly misaligned data in certain columns--however, this is due to some NULL cells. Therefore, I set a lot of "DEFAULT NULL" datatypes. Additionally, many country, city, and player names have more than 20 characters--so I set the VARCHAR limit to 50 for these columns.  
ubuntu@ip-172-31-21-131:~/baseballdata$ column -s, -t < Master.csv
playerID   birthYear   birthMonth  birthDay                birthCountry    birthState                birthCity                   deathYear        deathMonth               deathDay                                   deathCountry     deathState            deathCity                     nameFirst                  nameLast                     nameGiven                                    weight      height      bats        throws      debut       finalGame   retroID    bbrefID
aardsda01  1981        12          27                      USA             CO                        Denver                      David            Aardsma                  David Allan                                205              75                    R                             R                          2004-04-06                   2013-09-28                                   aardd001    aardsda01
aaronha01  1934        2           5                       USA             AL                        Mobile                      Hank             Aaron                    Henry Louis                                180              72                    R                             R                          1954-04-13                   1976-10-03                                   aaroh101    aaronha01
aaronto01  1939        8           5                       USA             AL                        Mobile                      1984             8                        16                                         USA              GA                    Atlanta                       Tommie                     Aaron                        Tommie Lee                                   190         75          R           R           1962-04-10  1971-09-26  aarot101   aaronto01
wrighal01  1912        11          11                      USA             CA                        San Francisco               1998             11                       13                                         USA              CA                    Oakland                       Al                         Wright                       Albert Edgar                                 170         73          R           R           1933-04-25  1933-05-05  wriga102   wrighal01
wrighal99  1842        3           31                      USA             NY                        New York                    1905             4                        20                                         USA              NY                    New York                      Al                         Wright                       Alfred Hector                                wriga801    wrighal99


2. psql
3. \connect baseball
4. Copy/paste:
    CREATE TABLE IF NOT EXISTS Master 
    (playerID varchar(20) DEFAULT NULL,
	birthYear int DEFAULT NULL,
    birthMonth int DEFAULT NULL,
	birthDay int DEFAULT NULL,
    birthCountry varchar(50) DEFAULT NULL,
    birthState varchar(50) DEFAULT NULL,
    birthCity varchar(50) DEFAULT NULL,
    deathYear int DEFAULT NULL,
    deathMonth int DEFAULT NULL,
    deathDay int DEFAULT NULL,
    deathCountry varchar(50) DEFAULT NULL,
    deathState varchar(50) DEFAULT NULL,
    deathCity varchar(50) DEFAULT NULL,
    nameFirst varchar(50) DEFAULT NULL,
    nameLast varchar(50) DEFAULT NULL,
    nameGiven varchar(50) DEFAULT NULL,
    weight int DEFAULT NULL,
    height int DEFAULT NULL,
    bats varchar(20) DEFAULT NULL,
    throws varchar(20) DEFAULT NULL,
    debut varchar(20) DEFAULT NULL,
    finalGame varchar(20) DEFAULT NULL,
    retroID varchar(20) DEFAULT NULL,
    bbrefID varchar(20) DEFAULT NULL
    );

5. Copy/paste:
    COPY Master FROM '/home/ubuntu/baseballdata/Master.csv' DELIMITER ',' CSV HEADER;

In [9]:
#LIMIT was not specified in the question--so I did not set a limit
query = """
rollback;
SELECT playerID, (DATE(finalGame)-DATE(debut))
FROM Master
WHERE debut IS NOT NULL
GROUP BY playerID, (DATE(finalGame)-DATE(debut))
ORDER BY (DATE(finalGame)-DATE(debut)) DESC;
"""
cursor.execute(query)
cursor.fetchall()

[('altroni01', 12862),
 ('orourji01', 11836),
 ('minosmi01', 11492),
 ('olearch01', 11126),
 ('lathaar01', 10678),
 ('mcguide01', 10192),
 ('jennihu01', 9954),
 ('eversjo01', 9897),
 ('ryanno01', 9873),
 ('streega01', 9868),
 ('ansonca01', 9647),
 ('moyerja01', 9477),
 ('johnto01', 9393),
 ('francju01', 9278),
 ('broutda01', 9234),
 ('oroscje01', 8941),
 ('gleaski01', 8894),
 ('henderi01', 8853),
 ('morgami01', 8849),
 ('quinnja01', 8849),
 ('ryanja01', 8797),
 ('newsobo01', 8772),
 ('wynnea01', 8766),
 ('wallabo01', 8752),
 ('houghch01', 8749),
 ('kaatji01', 8734),
 ('collied01', 8720),
 ('fiskca01', 8678),
 ('vizquom01', 8584),
 ('griffcl01', 8579),
 ('oconnja01', 8572),
 ('eckerde01', 8568),
 ('spahnwa01', 8566),
 ('niekrph01', 8565),
 ('hartlgr01', 8541),
 ('rosepe01', 8532),
 ('clemero02', 8524),
 ('ruffire01', 8507),
 ('coonejo01', 8503),
 ('maranra01', 8419),
 ('raineti01', 8419),
 ('cobbty01', 8413),
 ('carltst01', 8412),
 ('schrepa01', 8407),
 ('dempsri01', 8405),
 ('lyonste01

```
Answer:
[('altroni01', 12862),
 ('orourji01', 11836),
 ('minosmi01', 11492),
 ('olearch01', 11126),
 ('lathaar01', 10678),
 ('mcguide01', 10192),
 ('jennihu01', 9954),
 ('eversjo01', 9897),
 ('ryanno01', 9873),
 ('streega01', 9868),
 ('ansonca01', 9647),
 ('moyerja01', 9477),
 ('johnto01', 9393),
 ('francju01', 9278),
 ('broutda01', 9234),
 ('oroscje01', 8941),
 ('gleaski01', 8894),
 ('henderi01', 8853),
 ('morgami01', 8849),
 ('quinnja01', 8849),
 ('ryanja01', 8797),
 ('newsobo01', 8772),
 ('wynnea01', 8766),
 ('wallabo01', 8752),
 ('houghch01', 8749),
 ('kaatji01', 8734),
 ('collied01', 8720),
 ('fiskca01', 8678),
 ('vizquom01', 8584),
 ('griffcl01', 8579),
 ('oconnja01', 8572),
 ('eckerde01', 8568),
 ('spahnwa01', 8566),
 ('niekrph01', 8565),
 ('hartlgr01', 8541),
 ('rosepe01', 8532),
 ('clemero02', 8524),
 ('ruffire01', 8507),
 ('coonejo01', 8503),
 ('maranra01', 8419),
 ('raineti01', 8419),
 ('cobbty01', 8413),
 ('carltst01', 8412),
 ('schrepa01', 8407),
 ('dempsri01', 8405),
 ('lyonste01', 8357),
 ('staubru01', 8216),
 ('aaronha01', 8209),
 ('yastrca01', 8209),
 ('blylebe01', 8157),
 ('suttodo01', 8153),
 ('gossari01', 8149),
 ('nuxhajo01', 8149),
 ('mayswi01', 8143),
 ('pennohe01', 8140),
 ('winfida01', 8139),
 ('bendech01', 8128),
 ('perezto01', 8106),
 ('maddugr01', 8060),
 ('martide01', 8048),
 ('musiast01', 8047),
 ('robinbr01', 8001),
 ('hornsro01', 7984),
 ('bushgu01', 7922),
 ('davisha01', 7921),
 ('baineha01', 7840),
 ('slaugen01', 7833),
 ('willite01', 7832),
 ('perryga01', 7830),
 ('dykesji01', 7818),
 ('bondsba01', 7789),
 ('jonessa01', 7777),
 ('kalinal01', 7769),
 ('killeha01', 7765),
 ('clarkfr01', 7754),
 ('vernomi01', 7752),
 ('ottme01', 7745),
 ('smoltjo01', 7739),
 ('thompsa01', 7739),
 ('francjo01', 7738),
 ('youngcy01', 7730),
 ('griffke02', 7728),
 ('rixeyep01', 7715),
 ('sewellu01', 7702),
 ('thomeji01', 7700),
 ('sheffga01', 7697),
 ('mccarti01', 7696),
 ('nettlgr01', 7696),
 ('mitchcl01', 7690),
 ('johnsra05', 7689),
 ('niekrjo01', 7684),
 ('morgajo02', 7680),
 ('valoel01', 7679),
 ('reussje01', 7676),
 ('beckbo01', 7674),
 ('glavito02', 7668),
 ('speaktr01', 7658),
 ('mccovwi01', 7647),
 ('luquedo01', 7646),
 ('phillda01', 7639),
 ('ruthba01', 7628),
 ('bucknbi01', 7556),
 ('gordoto01', 7542),
 ('cavarph01', 7539),
 ('peitzhe01', 7533),
 ('molitpa01', 7478),
 ('dahlebi01', 7477),
 ('austiji01', 7475),
 ('murraed02', 7471),
 ('evansda01', 7469),
 ('robinfr02', 7459),
 ('batismi01', 7458),
 ('foxxji01', 7450),
 ('motama01', 7443),
 ('donovbi01', 7437),
 ('vanceda01', 7425),
 ('jacksre01', 7422),
 ('adamsba01', 7420),
 ('rodriiv01', 7405),
 ('wellsda01', 7395),
 ('wilheho01', 7388),
 ('simmoal01', 7382),
 ('fellebo01', 7378),
 ('brettge01', 7367),
 ('mclisca01', 7367),
 ('johnswa01', 7364),
 ('wagneho01', 7364),
 ('ripkeca01', 7362),
 ('grimmch01', 7360),
 ('crossla01', 7348),
 ('sierrru01', 7343),
 ('rhodear01', 7342),
 ('oliveda02', 7333),
 ('leonadu02', 7330),
 ('mcdanli01', 7330),
 ('tananfr01', 7327),
 ('applilu01', 7326),
 ('mesajo01', 7324),
 ('dawsoan01', 7323),
 ('ofarrbo01', 7323),
 ('stargwi01', 7322),
 ('darwida01', 7319),
 ('fairlro01', 7319),
 ('lajoina01', 7318),
 ('simmote01', 7316),
 ('caldwea01', 7312),
 ('simmocu01', 7308),
 ('mulhote01', 7300),
 ('gowdyha01', 7290),
 ('dicksmu01', 7289),
 ('gonzami01', 7284),
 ('leachto01', 7278),
 ('carisfr01', 7247),
 ('hoytwa01', 7235),
 ('pinielo01', 7225),
 ('honeyri01', 7191),
 ('hodgegi01', 7154),
 ('durocle01', 7138),
 ('yountro01', 7121),
 ('hartnga01', 7105),
 ('halldi01', 7102),
 ('rogerke01', 7101),
 ('mcgratu01', 7100),
 ('seaveto01', 7099),
 ('faberre01', 7096),
 ('hermaba01', 7095),
 ('whitede01', 7093),
 ('hardeme01', 7075),
 ('jonesfi01', 7074),
 ('downibr01', 7066),
 ('scheifr01', 7066),
 ('piercbi02', 7064),
 ('davisge01', 7057),
 ('dalyto01', 7048),
 ('biggicr01', 7035),
 ('ruelmu01', 7028),
 ('stiebda01', 7028),
 ('burdoja01', 7021),
 ('gwynnto01', 7020),
 ('rodrial01', 7019),
 ('callani01', 7017),
 ('hinespa01', 7013),
 ('campabe01', 7009),
 ('zimmech01', 7009),
 ('johnsja01', 7008),
 ('wakefti01', 6995),
 ('stairma01', 6993),
 ('blackle01', 6992),
 ('haineje01', 6992),
 ('orourfr01', 6985),
 ('alexape01', 6983),
 ('ricesa01', 6982),
 ('galaran01', 6981),
 ('stanaos01', 6969),
 ('palmeji01', 6965),
 ('jonesch06', 6962),
 ('daviswi02', 6961),
 ('seaneru01', 6961),
 ('lakefr01', 6960),
 ('trammal01', 6960),
 ('evansdw01', 6959),
 ('schilcu01', 6957),
 ('garbege01', 6954),
 ('johnssi01', 6953),
 ('joosted01', 6953),
 ('wanerpa01', 6953),
 ('sukefcl01', 6947),
 ('mcraeha01', 6945),
 ('merklfr01', 6945),
 ('perkicy01', 6945),
 ('alomasa02', 6939),
 ('hemslro01', 6937),
 ('careyma01', 6936),
 ('becklja01', 6933),
 ('woodlge01', 6933),
 ('haywora01', 6931),
 ('palmera01', 6931),
 ('cronijo01', 6930),
 ('lopezal01', 6928),
 ('winegra01', 6910),
 ('anderla02', 6904),
 ('mcbrige01', 6895),
 ('waltebu01', 6883),
 ('reuscri01', 6881),
 ('sugdejo01', 6876),
 ('heganji01', 6873),
 ('brownke01', 6871),
 ('kressre01', 6871),
 ('battijo01', 6865),
 ('merckke01', 6825),
 ('cramedo01', 6811),
 ('bartedi01', 6809),
 ('judgejo01', 6809),
 ('berrayo01', 6804),
 ('santibe01', 6784),
 ('gaettga01', 6779),
 ('carewro01', 6752),
 ('speiech01', 6752),
 ('surhobj01', 6752),
 ('davisch01', 6750),
 ('rijojo01', 6750),
 ('smithoz01', 6750),
 ('jonesdo01', 6748),
 ('wingoiv01', 6744),
 ('tayloto02', 6742),
 ('burgesm01', 6739),
 ('conceda01', 6737),
 ('wanerll01', 6732),
 ('bentoal01', 6731),
 ('johnssy01', 6730),
 ('mayru01', 6730),
 ('reesepe01', 6730),
 ('hawkila01', 6727),
 ('pettian01', 6727),
 ('ferreri01', 6722),
 ('riddljo02', 6722),
 ('walkedi02', 6722),
 ('giambja01', 6718),
 ('troutdi01', 6714),
 ('lisenho01', 6712),
 ('rootch01', 6712),
 ('wilheka01', 6705),
 ('koosmje01', 6704),
 ('riverma01', 6701),
 ('mcinnst01', 6685),
 ('sprinru01', 6683),
 ('sosasa01', 6679),
 ('jeterde01', 6676),
 ('elybo01', 6670),
 ('alexado01', 6668),
 ('schofdi01', 6663),
 ('bressru01', 6659),
 ('osteecl01', 6657),
 ('parkeda01', 6656),
 ('schoere01', 6655),
 ('roberro01', 6651),
 ('nelsoca01', 6649),
 ('mcaleji01', 6648),
 ('willicy01', 6640),
 ('weathda01', 6637),
 ('coffmdi01', 6636),
 ('finlest01', 6635),
 ('mcgrifr01', 6634),
 ('klinero01', 6627),
 ('larkiba01', 6626),
 ('friscfr01', 6624),
 ('foxne01', 6622),
 ('tiantlu01', 6621),
 ('schanwa01', 6618),
 ('roushed01', 6612),
 ('stantmi02', 6611),
 ('bresnro01', 6610),
 ('fernato01', 6610),
 ('turnete01', 6609),
 ('candejo01', 6604),
 ('thomafr04', 6602),
 ('bakerdu01', 6601),
 ('gonzalu01', 6599),
 ('dickebi01', 6598),
 ('watsobo01', 6596),
 ('whitalo01', 6596),
 ('brocklo01', 6594),
 ('mclemma01', 6594),
 ('jacksmi02', 6593),
 ('leiteal01', 6592),
 ('parrila02', 6592),
 ('snydepo01', 6592),
 ('boonebo01', 6591),
 ('hudliwi01', 6591),
 ('cuellmi01', 6590),
 ('heilmha01', 6590),
 ('jenkife01', 6590),
 ('kennebo01', 6590),
 ('baylodo01', 6588),
 ('groteje01', 6587),
 ('cartega01', 6586),
 ('grimebu01', 6584),
 ('wheatza01', 6584),
 ('bankser01', 6583),
 ('applepe01', 6581),
 ('crawfsa01', 6580),
 ('gehrich01', 6579),
 ('normafr01', 6579),
 ('reedro01', 6578),
 ('foremfr01', 6568),
 ('wiseri01', 6566),
 ('ryanji01', 6559),
 ('yosted01', 6555),
 ('sauerha01', 6551),
 ('keelewi01', 6548),
 ('fitzsfr01', 6547),
 ('zachato01', 6531),
 ('hamnegr01', 6530),
 ('aloumo01', 6529),
 ('cruzjo01', 6513),
 ('sutclri01', 6505),
 ('duffyhu01', 6502),
 ('mondari01', 6500),
 ('sandesc01', 6492),
 ('griffke01', 6488),
 ('mcclubo01', 6487),
 ('herriar01', 6485),
 ('murcebo01', 6485),
 ('seiboso01', 6478),
 ('garvest01', 6473),
 ('wilsowi02', 6463),
 ('gerhajo01', 6449),
 ('howeldi01', 6433),
 ('myersgr01', 6432),
 ('ramirma02', 6425),
 ('davalvi01', 6390),
 ('russebi01', 6386),
 ('hoffmtr01', 6385),
 ('javiest01', 6383),
 ('timlimi01', 6383),
 ('cardejo02', 6382),
 ('dunstsh01', 6382),
 ('abernte02', 6380),
 ('clemero01', 6379),
 ('plesada01', 6379),
 ('snidedu01', 6379),
 ('hamptmi01', 6378),
 ('lowebo01', 6378),
 ('donovpa01', 6377),
 ('mcphebi01', 6375),
 ('pinsova01', 6375),
 ('wilsoji01', 6375),
 ('mantlmi01', 6374),
 ('aparilu01', 6373),
 ('mizejo01', 6372),
 ('burksel01', 6365),
 ('mcgeewi01', 6355),
 ('uhlege01', 6355),
 ('pizarju01', 6354),
 ('daviser01', 6350),
 ('lollash01', 6349),
 ('mastewa02', 6349),
 ('boggswa01', 6348),
 ('mancugu01', 6343),
 ('owenmi01', 6341),
 ('davissp01', 6337),
 ('saberbr01', 6334),
 ('hendrge01', 6330),
 ('sheame01', 6328),
 ('bordepa01', 6321),
 ('tennefr02', 6321),
 ('whitefr01', 6319),
 ('martibu01', 6316),
 ('frymawo01', 6313),
 ('crandde01', 6309),
 ('nichobi01', 6307),
 ('phillto02', 6306),
 ('sewelri01', 6305),
 ('millebo04', 6303),
 ('blakesh01', 6298),
 ('quinnjo02', 6296),
 ('wrighja01', 6296),
 ('seymocy01', 6294),
 ('corcoto01', 6290),
 ('bluegos01', 6289),
 ('maulal01', 6289),
 ('paigesa01', 6287),
 ('bluevi01', 6283),
 ('galvipu01', 6282),
 ('lawve01', 6279),
 ('kellejo01', 6277),
 ('randowi01', 6277),
 ('ausmubr01', 6276),
 ('isrinja01', 6274),
 ('bellbu01', 6272),
 ('henrybi01', 6269),
 ('ibanera01', 6268),
 ('willibi01', 6267),
 ('belanma01', 6265),
 ('mussimi01', 6265),
 ('woodwi01', 6262),
 ('farredu01', 6261),
 ('suttoez01', 6257),
 ('bergmda01', 6249),
 ('schalra01', 6244),
 ('picinva01', 6243),
 ('quirkja01', 6240),
 ('griffal01', 6238),
 ('harrato01', 6238),
 ('penato01', 6236),
 ('hortowi01', 6235),
 ('jorgemi01', 6235),
 ('harrile01', 6234),
 ('brocado01', 6233),
 ('jacklfr01', 6233),
 ('klippjo01', 6233),
 ('flanami01', 6232),
 ('mayle01', 6232),
 ('martied01', 6231),
 ('pacioto01', 6231),
 ('vizcajo01', 6230),
 ('pascuca02', 6229),
 ('macfada01', 6228),
 ('connoro01', 6226),
 ('davisma01', 6225),
 ('coninje01', 6223),
 ('edmonji01', 6221),
 ('morrija02', 6221),
 ('oliveal01', 6221),
 ('davisto02', 6220),
 ('dwyerji01', 6220),
 ('moorejo01', 6220),
 ('hebneri01', 6219),
 ('peckiro01', 6219),
 ('cromawa01', 6218),
 ('gosligo01', 6218),
 ('kraneed01', 6217),
 ('martipe02', 6215),
 ('jacksgr01', 6214),
 ('greenha01', 6213),
 ('touchcl01', 6213),
 ('fingero01', 6211),
 ('deandi01', 6209),
 ('bellja01', 6208),
 ('mcmahdo02', 6208),
 ('truckvi01', 6208),
 ('oneilst01', 6206),
 ('fostege01', 6205),
 ('coopewa01', 6204),
 ('marquru01', 6202),
 ('damonjo01', 6199),
 ('coneda01', 6198),
 ('hargrbu01', 6197),
 ('jonesda01', 6196),
 ('clarkja01', 6195),
 ('cuyleki01', 6194),
 ('chambch01', 6190),
 ('rudoldi01', 6190),
 ('kellyge01', 6188),
 ('sadecra01', 6183),
 ('otisam01', 6178),
 ('traynpi01', 6177),
 ('ceronri01', 6172),
 ('fordwh01', 6168),
 ('torremi01', 6165),
 ('suppaje01', 6160),
 ('smithle02', 6148),
 ('valenfe01', 6146),
 ('jamiech01', 6145),
 ('byerlbu01', 6143),
 ('hershor01', 6143),
 ('embreal01', 6142),
 ('stewada01', 6142),
 ('tanneje01', 6142),
 ('lemonbo01', 6139),
 ('burdele01', 6137),
 ('kuheljo01', 6128),
 ('beniqju01', 6113),
 ('grimsja01', 6109),
 ('torrejo01', 6109),
 ('ewingbu01', 6104),
 ('fregoji01', 6103),
 ('schmimi01', 6102),
 ('doakbi01', 6098),
 ('murphda05', 6094),
 ('penaor01', 6094),
 ('robinbi02', 6089),
 ('piersji01', 6080),
 ('johnsfr01', 6069),
 ('wallide01', 6060),
 ('sullibi03', 6058),
 ('schaege01', 6046),
 ('reedje02', 6023),
 ('colonba01', 6020),
 ('parkch01', 6020),
 ('goodedw01', 6019),
 ('crosefr01', 6018),
 ('eisenji01', 6017),
 ('montawi01', 6017),
 ('hoopeha01', 6015),
 ('cairomi01', 6013),
 ('kentje01', 6012),
 ('martipe01', 6012),
 ('grovele01', 6011),
 ('moseswa01', 6010),
 ('matheed01', 6009),
 ('clemeja01', 6006),
 ('robinwi01', 6006),
 ('adcocjo01', 6005),
 ('boutoji01', 6004),
 ('mathebo01', 6003),
 ('vaughar01', 6002),
 ('cepedor01', 6001),
 ('wertzvi01', 6001),
 ('lombaer01', 5999),
 ('rowesc01', 5995),
 ('strawda01', 5994),
 ('myattgl01', 5991),
 ('burgmto01', 5985),
 ('gibsobo01', 5985),
 ('keenaji01', 5983),
 ('alomaro01', 5980),
 ('lolicmi01', 5978),
 ('jurgebi01', 5972),
 ('finlech01', 5966),
 ('facero01', 5965),
 ('muellra01', 5965),
 ('ricede01', 5965),
 ('elberki01', 5960),
 ('shaffor01', 5957),
 ('kittrma01', 5954),
 ('guarded01', 5953),
 ('perryji01', 5948),
 ('gumpera01', 5946),
 ('higgipi01', 5940),
 ('grichbo01', 5939),
 ('desauge01', 5936),
 ('vanhage01', 5934),
 ('mazerbi01', 5933),
 ('worthal01', 5932),
 ('sullibi04', 5930),
 ('mcculcl01', 5929),
 ('planked01', 5929),
 ('kotsama01', 5924),
 ('pikeli01', 5924),
 ('wardjo01', 5920),
 ('gardnla01', 5917),
 ('glassja01', 5917),
 ('howest01', 5915),
 ('majesha01', 5914),
 ('tiefebo01', 5913),
 ('smithsh01', 5912),
 ('alvarwi01', 5910),
 ('bergmo01', 5910),
 ('podrejo01', 5909),
 ('rolensc01', 5907),
 ('shousbr01', 5906),
 ('hairsje01', 5905),
 ('blanche01', 5904),
 ('heltoto01', 5902),
 ('welchbo01', 5896),
 ('willima04', 5894),
 ('cashno01', 5893),
 ('jonesan01', 5893),
 ('mathech01', 5893),
 ('walkela01', 5891),
 ('easleda01', 5890),
 ('bunniji01', 5889),
 ('drabomo01', 5887),
 ('webbsk01', 5886),
 ('butlebr01', 5883),
 ('pappami01', 5883),
 ('hunteto01', 5881),
 ('cansejo01', 5878),
 ('oneilpa01', 5878),
 ('swindgr01', 5877),
 ('whitede03', 5877),
 ('benchjo01', 5876),
 ('bradlbi01', 5876),
 ('manushe01', 5876),
 ('porteda02', 5876),
 ('abreubo01', 5875),
 ('roofph01', 5875),
 ('gantnji01', 5874),
 ('rodriau01', 5874),
 ('olerujo01', 5873),
 ('lynnfr01', 5872),
 ('chapmbe01', 5871),
 ('ortizda01', 5871),
 ('sandbry01', 5870),
 ('nichoki01', 5868),
 ('nixonot01', 5868),
 ('posadjo01', 5868),
 ('bahnsst01', 5867),
 ('hernaro01', 5867),
 ('lowede01', 5867),
 ('wallati01', 5867),
 ('carrch01', 5866),
 ('grossgr01', 5866),
 ('herbera01', 5865),
 ('konerpa01', 5865),
 ('servisc01', 5865),
 ('alouje01', 5863),
 ('bailebo01', 5862),
 ('sievero01', 5862),
 ('camermi01', 5860),
 ('loftoke01', 5859),
 ('smithre06', 5859),
 ('whiteea01', 5859),
 ('roepr01', 5857),
 ('sheckji01', 5857),
 ('amesre01', 5855),
 ('burkejo03', 5855),
 ('counscr01', 5855),
 ('anderga01', 5854),
 ('claytro01', 5854),
 ('cartyri01', 5852),
 ('snowjt01', 5851),
 ('princto01', 5850),
 ('hernali01', 5849),
 ('pafkoan01', 5849),
 ('righeda01', 5846),
 ('wagnehe01', 5846),
 ('brownju01', 5845),
 ('bushjo01', 5844),
 ('myerbu01', 5842),
 ('tebbebi01', 5842),
 ('downial01', 5838),
 ('chancfr01', 5835),
 ('boyercl02', 5831),
 ('candito01', 5829),
 ('ericksc01', 5827),
 ('hammoch01', 5827),
 ('tejadmi01', 5827),
 ('washicl01', 5827),
 ('cedence01', 5826),
 ('gamblos01', 5825),
 ('tavarju01', 5825),
 ('grissma02', 5822),
 ('smithlo01', 5821),
 ('bridgto01', 5820),
 ('gromest01', 5820),
 ('sandere02', 5820),
 ('southbi01', 5818),
 ('hermabi01', 5816),
 ('gibsoki01', 5815),
 ('powelbo01', 5811),
 ('hernake01', 5807),
 ('covelst01', 5806),
 ('medwijo01', 5805),
 ('trillma01', 5805),
 ('aloufe01', 5799),
 ('doyleja01', 5798),
 ('gehrilo01', 5798),
 ('mogrige01', 5798),
 ('kleinch01', 5795),
 ('brownto01', 5794),
 ('ceyro01', 5791),
 ('breweji01', 5790),
 ('ashbyal01', 5789),
 ('coopece01', 5786),
 ('wyattwh01', 5784),
 ('freembu01', 5775),
 ('livinpa01', 5765),
 ('blairpa01', 5763),
 ('wilcomi01', 5759),
 ('strunam01', 5756),
 ('castrju01', 5754),
 ('floydcl01', 5751),
 ('gonzaju03', 5751),
 ('gantro01', 5740),
 ('forscke01', 5737),
 ('crigelo01', 5733),
 ('millest01', 5733),
 ('cicerjo01', 5731),
 ('johnsde01', 5729),
 ('myershy01', 5729),
 ('ridzist01', 5727),
 ('cormirh01', 5725),
 ('finnelo01', 5717),
 ('delgaca01', 5700),
 ('newhoha01', 5695),
 ('bellira01', 5694),
 ('harpebr01', 5691),
 ('etchean01', 5685),
 ('vosbeed01', 5684),
 ('bowala01', 5661),
 ('bonilbo01', 5660),
 ('wittbo01', 5659),
 ('guilloz01', 5654),
 ('rudijo01', 5654),
 ('forstte01', 5653),
 ('rojasco01', 5653),
 ('sundbji01', 5652),
 ('grohhe01', 5651),
 ('fournja01', 5650),
 ('baergca01', 5648),
 ('langsma01', 5648),
 ('burnsge02', 5647),
 ('burkeje01', 5646),
 ('giustda01', 5646),
 ('northro01', 5646),
 ('slatoji01', 5646),
 ('crabtes01', 5645),
 ('lucasre01', 5644),
 ('seguidi01', 5644),
 ('goodmbi01', 5643),
 ('hackst01', 5643),
 ('warnelo01', 5643),
 ('cuccito01', 5642),
 ('harribi01', 5642),
 ('schumha02', 5642),
 ('suscege01', 5640),
 ('westsa01', 5639),
 ('moneydo01', 5638),
 ('schripo01', 5638),
 ('hallmbi01', 5634),
 ('odoulle01', 5633),
 ('bettshu01', 5632),
 ('mannle01', 5632),
 ('bennech01', 5631),
 ('shantbo01', 5630),
 ('dimagjo01', 5628),
 ('frienbo01', 5628),
 ('hadlebu01', 5628),
 ('lindsji01', 5628),
 ('gracema01', 5627),
 ('carpech01', 5622),
 ('millebi02', 5621),
 ('galanau01', 5619),
 ('lockwsk01', 5619),
 ('renteed01', 5619),
 ('rogelbi01', 5612),
 ('severha01', 5612),
 ('johnsji01', 5610),
 ('dempsry01', 5608),
 ('ramirar01', 5605),
 ('kellyki01', 5603),
 ('rizzuph01', 5603),
 ('murphjo04', 5598),
 ('collida02', 5597),
 ('martida01', 5593),
 ('bannifl01', 5592),
 ('ontivst02', 5588),
 ('mcmilro01', 5587),
 ('forceda01', 5586),
 ('groatdi01', 5582),
 ('tayloza02', 5579),
 ('beltrad01', 5577),
 ('hevinjo02', 5577),
 ('lacyle01', 5573),
 ('pippwa01', 5572),
 ('mahayro01', 5571),
 ('mullira01', 5571),
 ('powelja01', 5571),
 ('mayja01', 5570),
 ('mageesh01', 5568),
 ('gurala01', 5567),
 ('hendeke01', 5566),
 ('polanpl01', 5566),
 ('aguilri01', 5565),
 ('longhe01', 5565),
 ('rhoderi01', 5565),
 ('sislege01', 5565),
 ('willibe02', 5565),
 ('bentoru01', 5564),
 ('lylesp01', 5564),
 ('norrimi01', 5564),
 ('forscbo01', 5559),
 ('burroje01', 5557),
 ('laniema01', 5554),
 ('donlimi01', 5552),
 ('joynewa01', 5546),
 ('kingmda01', 5546),
 ('cardele01', 5541),
 ('gomezch02', 5540),
 ('cartejo01', 5539),
 ('millwke01', 5539),
 ('powelja03', 5537),
 ('tekulke01', 5536),
 ('templga01', 5535),
 ('ortajo01', 5534),
 ('dietrbi01', 5532),
 ('hernajo01', 5532),
 ('bushodo01', 5531),
 ('startjo01', 5531),
 ('byrdati01', 5529),
 ('donovdi01', 5528),
 ('fieldji01', 5528),
 ('reedri01', 5527),
 ('bancrda01', 5526),
 ('mcgwima01', 5525),
 ('zeileto01', 5525),
 ('roystje01', 5524),
 ('offerjo01', 5523),
 ('pfefffr01', 5523),
 ('martiti02', 5522),
 ('oberkke01', 5522),
 ('ehmkeho01', 5519),
 ('velarra01', 5519),
 ('grudzma01', 5518),
 ('jonesto02', 5518),
 ('raffeke01', 5517),
 ('onsloed01', 5516),
 ('wickmbo01', 5515),
 ('milancl01', 5513),
 ('polleho01', 5513),
 ('snydefr01', 5513),
 ('harrebu01', 5512),
 ('samueju01', 5512),
 ('delahed01', 5511),
 ('mcgowbe01', 5510),
 ('oglivbe01', 5510),
 ('bandosa01', 5509),
 ('freylo01', 5509),
 ('bottoji01', 5508),
 ('sweenmi01', 5508),
 ('torresa01', 5508),
 ('hubbeca01', 5507),
 ('piazzmi01', 5507),
 ('castivi02', 5506),
 ('derosma01', 5506),
 ('josefe01', 5504),
 ('matthga01', 5504),
 ('brownll01', 5503),
 ('collish01', 5503),
 ('lemonch01', 5503),
 ('cicoted01', 5502),
 ('heldwo01', 5502),
 ('chenbr01', 5501),
 ('garneph01', 5501),
 ('mintogr01', 5501),
 ('chaveer01', 5500),
 ('leifile01', 5500),
 ('pierzaj01', 5500),
 ('howarfr01', 5499),
 ('venturo01', 5499),
 ('wagnebi02', 5499),
 ('kirkped01', 5498),
 ('magadda01', 5498),
 ('milletr02', 5498),
 ('obriech01', 5498),
 ('grubbjo01', 5496),
 ('fletcel01', 5495),
 ('hanseda01', 5495),
 ('mcgrajo01', 5495),
 ('beltrca01', 5494),
 ('fettemi01', 5494),
 ('eversho01', 5493),
 ('hairsje02', 5493),
 ('ramospe01', 5493),
 ('gerbewa01', 5492),
 ('kleskry01', 5491),
 ('lopesda01', 5490),
 ('asprobo01', 5487),
 ('guerrvl01', 5487),
 ('freehbi01', 5486),
 ('remlimi01', 5486),
 ('robined01', 5485),
 ('crossmo01', 5484),
 ('dobsojo01', 5483),
 ('fasseje01', 5482),
 ('galehde01', 5482),
 ('hallaro01', 5482),
 ('hartbi01', 5482),
 ('schmijo01', 5480),
 ('knowlda01', 5479),
 ('sawatca01', 5478),
 ('clarkni01', 5477),
 ('mcmulke01', 5476),
 ('bushdo01', 5475),
 ('lockmwh01', 5468),
 ('mcfared01', 5467),
 ('huttoto01', 5466),
 ('riceji01', 5463),
 ('mcauldi01', 5462),
 ('callijo01', 5456),
 ('zaungr01', 5444),
 ('walkeha01', 5441),
 ('kessido01', 5440),
 ('appieke01', 5437),
 ('darwibo01', 5436),
 ('sistisi01', 5434),
 ('questjo01', 5431),
 ('slaugdo01', 5431),
 ('gullibi01', 5429),
 ('heintke01', 5428),
 ('sommeru01', 5421),
 ('valenjo03', 5419),
 ('hinchbi01', 5416),
 ('whitter01', 5407),
 ('lampde01', 5403),
 ('aguirha01', 5401),
 ('murphda02', 5400),
 ('thomafr03', 5400),
 ('bailebi01', 5396),
 ('gonzaal02', 5395),
 ('foliti01', 5391),
 ('smithel01', 5391),
 ('leeth01', 5386),
 ('maricju01', 5384),
 ('hillejo01', 5377),
 ('muellhe01', 5376),
 ('trachst01', 5375),
 ('hallme01', 5374),
 ('mccormi03', 5374),
 ('hogsech01', 5372),
 ('hillca01', 5366),
 ('reardje01', 5366),
 ('lowenjo01', 5358),
 ('penaal01', 5357),
 ('postwa01', 5347),
 ('gumbeha01', 5343),
 ('floodcu01', 5341),
 ('brunege01', 5339),
 ('jonnabu01', 5339),
 ('kreutch01', 5338),
 ('braunst01', 5297),
 ('lansfca01', 5293),
 ('bagweje01', 5291),
 ('clarkwi02', 5290),
 ('girarjo01', 5290),
 ('jordabr01', 5288),
 ('smithge01', 5288),
 ('harpeto01', 5287),
 ('burrira01', 5285),
 ('garcifr02', 5284),
 ('walkege02', 5283),
 ('hattogr01', 5282),
 ('walkehu01', 5282),
 ('keyji01', 5280),
 ('kluszte01', 5280),
 ('derripa01', 5278),
 ('francti01', 5278),
 ('cannich01', 5277),
 ('chaseha01', 5277),
 ('ashburi01', 5276),
 ('gibsofr01', 5276),
 ('maysca01', 5276),
 ('osterfr01', 5276),
 ('nathajo01', 5275),
 ('stewale01', 5275),
 ('daubeja01', 5273),
 ('hoeftbi01', 5273),
 ('hudsosi01', 5273),
 ('villoro01', 5273),
 ('stalege01', 5272),
 ('tinkejo01', 5272),
 ('richapa01', 5271),
 ('waitked01', 5271),
 ('fletcsc01', 5270),
 ('walberu01', 5270),
 ('alicelu01', 5268),
 ('hoagmy01', 5268),
 ('johnsha01', 5268),
 ('farnsky01', 5267),
 ('leede02', 5266),
 ('shortch02', 5266),
 ('kendaja01', 5264),
 ('hutchfr01', 5262),
 ('byrneto01', 5261),
 ('caseyhu01', 5261),
 ('maniocl01', 5261),
 ('yorkto01', 5259),
 ('doerrbo01', 5253),
 ('greggve01', 5249),
 ('thondi01', 5248),
 ('geronce01', 5247),
 ('pavledo01', 5247),
 ('harrigr01', 5245),
 ('torgeea01', 5244),
 ('williwo02', 5244),
 ('travice01', 5243),
 ('hunteca01', 5240),
 ('marshmi01', 5238),
 ('seguida01', 5237),
 ('tenacge01', 5237),
 ('boyerke01', 5233),
 ('tincube01', 5230),
 ('driesda01', 5229),
 ('gagnegr01', 5228),
 ('liebejo01', 5227),
 ('heathcl01', 5226),
 ('weyhigu01', 5224),
 ('smithbo02', 5223),
 ...]    
```

In [10]:
#Of note: There were many "NULL" finalGame and debut values
query = """
rollback;
SELECT COUNT(playerID)
FROM Master
WHERE debut IS NULL;
"""
cursor.execute(query)
cursor.fetchall()

[(189,)]

# What is the distribution of debut months? *Hint:* Look at the `DATE` and [`EXTRACT`](https://www.postgresql.org/docs/current/static/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT) functions.

In [11]:
#These results kind of make sense to me because most sports are not year-round and according to Wikipedia, the Major League Baseball regular season runs from late March/early April to late September/early October--so it makes sense why there's a peak in April to begin a new season and toward the end of the season (September) if they're trying to get new players to rehearse playing in the big leagues to prepare for the next season AND/OR if the regular players get injured by the end of the season and they need to use more players from their bench. The recruiting (scouting and hiring) timeline is another factor, but I don't understand how that works and imagine it to be a year-round process that may or may not affect the distribution of debut months.  
query = """
rollback;
SELECT EXTRACT(MONTH FROM (DATE(DEBUT))), COUNT(playerID)
FROM Master
GROUP BY EXTRACT(MONTH FROM (DATE(DEBUT)))
ORDER BY EXTRACT(MONTH FROM (DATE(DEBUT)));
"""
cursor.execute(query)
cursor.fetchall()

[(3.0, 41),
 (4.0, 4711),
 (5.0, 2230),
 (6.0, 1893),
 (7.0, 1978),
 (8.0, 1943),
 (9.0, 5061),
 (10.0, 308),
 (None, 189)]

```
ANSWER: 
[(3.0, 41),
 (4.0, 4711),
 (5.0, 2230),
 (6.0, 1893),
 (7.0, 1978),
 (8.0, 1943),
 (9.0, 5061),
 (10.0, 308),
 (None, 189)] 
```

# What is the effect of table join order on mean salary for the players listed in the main (master) table? *Hint:* Perform two different queries, one that joins on playerID in the salary table and other that joins on the same column in the master table. You will have to use left joins for each since right joins are not currently supported with SQLalchemy.

In [12]:
#The order of "MEAN SALARY" in the joined tables keeps the order of whichever table was listed under "SELECT" (i.e., Master.playerID). Below is "Salaries LEFT JOIN Master"--which lists the table in the order of how "Master" was listed. Also note that there are ZERO NULL values in this table.  
query = """
rollback;
SELECT Master.playerID, AVG(salary)
FROM Salaries
LEFT JOIN Master ON Salaries.playerID = Master.playerID
GROUP BY Master.playerID
LIMIT 50;
"""
cursor.execute(query)
cursor.fetchall()

[('ramirju01', 250000.0),
 ('rodrica01', 138000.0),
 ('saundto01', 266875.0),
 ('murphda07', 2172581.66666667),
 ('estessh01', 1871291.66666667),
 ('melvibo01', 395625.0),
 ('florera01', 624000.0),
 ('daviswa01', 1284750.0),
 ('raabebr01', 160000.0),
 ('freemma02', 899785.714285714),
 ('damicje01', 800361.5),
 ('beimejo01', 931083.333333333),
 ('huntebr01', 302062.5),
 ('wilcomi01', 350000.0),
 ('hawpebr01', 3274166.66666667),
 ('kaplega01', 1089890.88888889),
 ('bankswi01', 243083.333333333),
 ('lucrojo01', 588666.666666667),
 ('greerke01', 109000.0),
 ('hortori01', 252583.333333333),
 ('baldwja01', 1646750.0),
 ('cottohe01', 523333.333333333),
 ('pauliro01', 672900.0),
 ('colemvi01', 1235192.30769231),
 ('ottavad01', 491000.0),
 ('sefcike01', 243833.333333333),
 ('sandesc02', 647000.0),
 ('brockch01', 471000.0),
 ('ardoida01', 335000.0),
 ('fossuca01', 1097416.66666667),
 ('taschja01', 556500.0),
 ('myersra01', 2866142.85714286),
 ('napolmi01', 3802857.14285714),
 ('wisede01', 443750

In [13]:
#Below is "Master LEFT JOIN Salaries"--which lists the table in the original order of however "Master" was listed due to "SELECT Master.playerID". Also note that there are NULL values in this table. 
query = """
rollback;
SELECT Master.playerID, AVG(salary)
FROM Master
LEFT JOIN Salaries ON Master.playerID = Salaries.playerID
GROUP BY Master.playerID
LIMIT 50; 
"""
cursor.execute(query)
cursor.fetchall()

[('jacobar01', None),
 ('kriegbi01', None),
 ('loesbi01', None),
 ('peppela01', None),
 ('cathete01', None),
 ('solommo01', None),
 ('westbu01', None),
 ('nashji01', None),
 ('ramirju01', 250000.0),
 ('krausha01', None),
 ('plaskel01', None),
 ('ziemst01', None),
 ('rodrica01', 138000.0),
 ('saundto01', 266875.0),
 ('murphda07', 2172581.66666667),
 ('smithch02', None),
 ('estessh01', 1871291.66666667),
 ('melvibo01', 395625.0),
 ('florera01', 624000.0),
 ('coogada02', None),
 ('jonesje02', None),
 ('foleyra01', None),
 ('gastjo01', None),
 ('daviswa01', 1284750.0),
 ('leveyji01', None),
 ('gilleji01', None),
 ('willijo99', None),
 ('hartnpa01', None),
 ('pheladi01', None),
 ('maysca01', None),
 ('johnsra02', None),
 ('spahnwa01', None),
 ('goldmjo01', None),
 ('teutna01', None),
 ('mcgeeda01', None),
 ('williwa01', None),
 ('pichero01', None),
 ('raabebr01', 160000.0),
 ('freemma02', 899785.714285714),
 ('mccloji01', None),
 ('trebeto99', None),
 ('nelsoto01', None),
 ('fletcge01', Non

In [14]:
#Since the order of the above tables are different, below I ORDER BY player and limit to the first 50 to compare the first 50 players/salaries between the different tables. Below are the first 50 players of the "Master LEFT JOIN Salaries" Table
query = """
rollback;
SELECT Master.playerID, AVG(salary)
FROM Master
LEFT JOIN Salaries ON Master.playerID = Salaries.playerID
WHERE salary IS NOT NULL
GROUP BY Master.playerID
ORDER BY Master.playerID
LIMIT 50; 
"""
#GROUP BY master.playerid, master.birthyear, master.birthmonth, master.birthday, master.birthcountry, master.birthstate, master.birthcity, master.deathyear, master.deathmonth, master.deathday, master.deathcountry, master.deathstate, master.deathcity, master.namefirst, master.namelast, master.namegiven, master.weight, master.height, master.bats, master.throws, master.debut, master.finalgame, master.retroid, master.bbrefid, salaries.yearid, salaries.teamid, salaries.lgid, salaries.playerid

cursor.execute(query)
cursor.fetchall()

[('aardsda01', 1322821.42857143),
 ('aasedo01', 575000.0),
 ('abadan01', 327000.0),
 ('abadfe01', 451500.0),
 ('abbotje01', 246250.0),
 ('abbotji01', 1440055.55555556),
 ('abbotku01', 470777.777777778),
 ('abbotky01', 129500.0),
 ('abbotpa01', 924428.571428571),
 ('abercre01', 327000.0),
 ('abernbr01', 257500.0),
 ('abnersh01', 144700.0),
 ('abreubo01', 7773729.125),
 ('abreuto01', 432666.666666667),
 ('accarje01', 654880.0),
 ('aceveal01', 1428550.0),
 ('acevejo01', 286500.0),
 ('aceveju01', 467071.428571429),
 ('ackerji01', 426500.0),
 ('ackledu01', 2400000.0),
 ('acostma01', 633750.0),
 ('acrema01', 133500.0),
 ('adamsda02', 540000.0),
 ('adamsjo02', 180500.0),
 ('adamsma01', 490000.0),
 ('adamsmi03', 2280133.33333333),
 ('adamsru01', 329500.0),
 ('adamste01', 1206181.81818182),
 ('adamswi02', 147833.333333333),
 ('adcocna01', 414000.0),
 ('adducji01', 70000.0),
 ('adenhni01', 400000.0),
 ('adkinjo01', 301000.0),
 ('afenitr01', 115000.0),
 ('affelje01', 2505250.0),
 ('agbaybe01', 32

In [15]:
#The first 50 players match up (i.e., both end at "aldrija...") when I exclude the NULL salaries in the "Master LEFT JOIN Salaries" table. 
query = """
rollback;
SELECT Master.playerID, AVG(salary) 
FROM Salaries
LEFT JOIN Master ON Salaries.playerID = Master.playerID
WHERE salary IS NOT NULL
GROUP BY Master.playerID
ORDER BY Master.playerID
LIMIT 50; 
"""
cursor.execute(query)
cursor.fetchall()

[('aardsda01', 1322821.42857143),
 ('aasedo01', 575000.0),
 ('abadan01', 327000.0),
 ('abadfe01', 451500.0),
 ('abbotje01', 246250.0),
 ('abbotji01', 1440055.55555556),
 ('abbotku01', 470777.777777778),
 ('abbotky01', 129500.0),
 ('abbotpa01', 924428.571428571),
 ('abercre01', 327000.0),
 ('abernbr01', 257500.0),
 ('abnersh01', 144700.0),
 ('abreubo01', 7773729.125),
 ('abreuto01', 432666.666666667),
 ('accarje01', 654880.0),
 ('aceveal01', 1428550.0),
 ('acevejo01', 286500.0),
 ('aceveju01', 467071.428571429),
 ('ackerji01', 426500.0),
 ('ackledu01', 2400000.0),
 ('acostma01', 633750.0),
 ('acrema01', 133500.0),
 ('adamsda02', 540000.0),
 ('adamsjo02', 180500.0),
 ('adamsma01', 490000.0),
 ('adamsmi03', 2280133.33333333),
 ('adamsru01', 329500.0),
 ('adamste01', 1206181.81818182),
 ('adamswi02', 147833.333333333),
 ('adcocna01', 414000.0),
 ('adducji01', 70000.0),
 ('adenhni01', 400000.0),
 ('adkinjo01', 301000.0),
 ('afenitr01', 115000.0),
 ('affelje01', 2505250.0),
 ('agbaybe01', 32

In [16]:
#To confirm the NULL values are the only differences affecting the "MEAN SALARY" between the two tables, I am comparing the lengths of the 2 table join orders. The merged tables in "Master LEFT JOIN Salaries" contains 13,686 distinct players that have a NULL salary. 
query = """
rollback;
SELECT COUNT(DISTINCT(Master.playerID))
FROM Master
LEFT JOIN Salaries ON Salaries.playerID = Master.playerID
WHERE salary IS NULL; 
"""
cursor.execute(query)
cursor.fetchall()

[(13686,)]

In [17]:
#The "IS NOT NULL" distinct player count was 4,668--meaning that Master contains all the same players in the Salaries table, but Salaries does NOT contain all the players that are in the Master table.
query = """
rollback;
SELECT COUNT(DISTINCT(Master.playerID))
FROM Master
LEFT JOIN Salaries ON Salaries.playerID = Master.playerID
WHERE salary IS NOT NULL; 
"""
cursor.execute(query)
cursor.fetchall()

[(4668,)]

In [18]:
#The merged tables in "Salaries LEFT JOIN Master" contains ZERO NULL salaries, but a total of 4,668 distinct players
query = """
rollback;
SELECT COUNT(DISTINCT(Master.playerID))
FROM Salaries
LEFT JOIN Master ON Salaries.playerID = Master.playerID; 
"""
cursor.execute(query)
cursor.fetchall()

[(4668,)]

In [19]:
#This would be the AVERAGE SALARY for "Master LEFT JOIN Salaries"--if I do NOT remove duplicate playerIDs. It appears that the average is calculating the sum of the salaries and dividing by the total count of playerIDs (since there are 23,956 matches of playerIDs shared between the Master and Salaries tables) 
query = """
rollback;
SELECT AVG(salary), SUM(salary), COUNT(DISTINCT(Master.playerID)), COUNT(Master.playerID), COUNT(DISTINCT(Salaries.playerID)), COUNT(Salaries.playerID)   
FROM Master
    LEFT JOIN Salaries
    ON Master.playerID = Salaries.playerID
; 
"""
cursor.execute(query)
cursor.fetchall()


[(1864357.1202204, 44662539172.0, 18354, 37642, 4668, 23956)]

In [20]:
#The calculated average with duplicate playerIDs is the same for "Salaries LEFT JOIN Master" ($1,864,357)--even though the 2 different merged tables have different lengths
query = """
rollback;
SELECT AVG(salary), SUM(salary), COUNT(DISTINCT(Salaries.playerID)), COUNT(Salaries.playerID), COUNT(DISTINCT(Master.playerID)), COUNT(Master.playerID)   
FROM Salaries
    LEFT JOIN Master
    ON Salaries.playerID = Master.playerID
; 
"""
cursor.execute(query)
cursor.fetchall()

[(1864357.1202204, 44662539172.0, 4668, 23956, 4668, 23956)]

In [21]:
#By removing duplicate playerIDs from both the Master and Salaries tables, we get a different mean ($9,567,810) because all the distinct counts of playerIDs are now 4668.  
query = """
rollback;
SELECT AVG(sum_salary), SUM(sum_salary), COUNT(distinct_players.playerID), COUNT(DISTINCT(distinct_players.playerID)), COUNT(distinct_salaries.playerID), COUNT(DISTINCT(distinct_salaries.playerID))
FROM (SELECT playerID FROM Master GROUP BY playerID) AS distinct_players 
    LEFT JOIN (SELECT playerID, SUM(salary) AS sum_salary FROM Salaries GROUP BY playerID) AS distinct_salaries
    ON distinct_players.playerID = distinct_salaries.playerID
; 
"""
cursor.execute(query)
cursor.fetchall()

[(9567810.44815767, 44662539172.0, 18354, 18354, 4668, 4668)]

In [22]:
#By removing duplicate playerIDs from both the Master and Salaries tables, we get a different mean ($9,567,810) because all the counts and distinct counts of playerIDs are now 4668.  
query = """
rollback;
SELECT AVG(sum_salary), SUM(sum_salary), COUNT(distinct_salaries.playerID), COUNT(DISTINCT(distinct_salaries.playerID)), COUNT(distinct_players.playerID), COUNT(DISTINCT(distinct_players.playerID))
FROM (SELECT playerID, SUM(salary) AS sum_salary FROM Salaries GROUP BY playerID) AS distinct_salaries
    LEFT JOIN (SELECT playerID FROM Master GROUP BY playerID) AS distinct_players
    ON distinct_salaries.playerID = distinct_players.playerID
; 
"""
cursor.execute(query)
cursor.fetchall()

[(9567810.44815767, 44662539172.0, 4668, 4668, 4668, 4668)]

```
Answer:
"Salaries LEFT JOIN Master" returns an AVERAGE salary for all players that appear in the Salary and Master list (4668 distinct players). With a smaller number of players in the denominator, I would expect the MEAN SALARY of the entire list (total salary divided by number of players) becomes larger. However, the AVG(Salary) divides by only the playerIDs that the two tables share--resulting in the same MEAN SALARY.  

"Master LEFT JOIN Salaries" returns an AVERAGE salary for all players that appear in the Salary and Master list (4668 distinct players), but also 13,686 distinct players where salary is null ("None"). With a larger number of players in the denominator, I would expect the MEAN SALARY of the entire list (total salary divided by number of players) to becomes smaller. However, the AVG(Salary) divides by only the playerIDs that the two tables share--resulting in the same MEAN SALARY.   

Because the calculated average in a SQL query for two joined tables is always based on the number of observations that are present in BOTH tables, the table JOIN order does NOT affect the mean salary. 
```

```
------------------------------------------------------------------
Opening AWS Machine in Jupyter Notebook:
    1. In terminal window:
        ssh -i ~/.ssh/aws_key.pem ubuntu@[insert IPv4 Public IP]
    2. In terminal window:
        jupyter notebook --port 9000
    3. In browser window:
        copy and paste one of these URLs:
        http://localhost:9000/?token=f2c83a4f8a7e7eb37b9e940330280e24e189b7173d507942
```